#!/usr/bin/env python3
"""Sixth pass: fix final remaining Korean."""

import os
import re
import subprocess

PROJECT_ROOT = "/home/runner/work/Beyond/Beyond"

FIXES = [
    # Small remaining items
    ('<p className="text-xs text-gray-500">마지막 catalog Sync</p>',
     '<p className="text-xs text-gray-500">Last Catalog Sync</p>'),
    ('<p>Link된 Modifiers 그룹이 없습니다.</p>',
     '<p>No linked modifier groups.</p>'),
    ('<p>아직 External POS로 Send되지 않았습니다. 향후 Loyverse 연동 시 여기서 Confirm Available합니다.</p>',
     '<p>Not yet sent to External POS. This will be available here after Loyverse integration is set up.</p>'),
    ('<span className="font-medium">장바구니 {cartCount}</span>',
     '<span className="font-medium">Cart ({cartCount})</span>'),
    ('<span className="text-gray-500">결제</span>',
     '<span className="text-gray-500">Payment</span>'),
    ('<span className="text-gray-500">총 Amount</span>',
     '<span className="text-gray-500">Total Amount</span>'),
    ('<span className="text-gray-700 font-medium">Subscriptions 발생 management</span>',
     '<span className="text-gray-700 font-medium">Subscription Occurrence Management</span>'),
    ('<span className="text-gray-700 font-medium">새 Products Add</span>',
     '<span className="text-gray-700 font-medium">Add New Product</span>'),
    ('<span className="text-gray-700">on-site 결제</span>',
     '<span className="text-gray-700">On-site Payment</span>'),
    ('<span className="text-sm font-medium text-gray-700">Inventory 추적 (tracksInventory)</span>',
     '<span className="text-sm font-medium text-gray-700">Inventory Tracking (tracksInventory)</span>'),
    ('<span>소계</span>', '<span>Subtotal</span>'),
    ('Predictions exist but no actual data to compare yet. Enter Actual Sales for the prediction date to compare performance.',
     'Predictions exist but no actual data to compare yet. Enter Actual Sales for the prediction date to compare performance.'),
    ('<strong>💡 안내:</strong>',
     '<strong>💡 Note:</strong>'),
    ('? "CSV 파일에 Data Rows이 없습니다"',
     '? "CSV file has no data rows"'),
    ('? "모든 Rows에 Error가 있습니다. CSV 형식을 Confirm해주세요"',
     '? "All rows have errors. Please check the CSV format"'),
    ('Inventory 추적\n', 'Inventory Tracking\n'),
    ('Loyverse catalog Sync를 when run Modifier 그룹이 automatically Create됩니다.',
     'Running Loyverse catalog Sync will automatically create Modifier groups.'),
    ('Loyverse catalog(Categories·Modifiers·Products)를 한 번에 Sync합니다',
     'Sync Loyverse catalog (Categories, Modifiers, Products) all at once'),
    ('externalCollect = { errors: [err instanceof Error ? err.message : "External Data Collecting Error 발생"] }',
     'externalCollect = { errors: [err instanceof Error ? err.message : "External data collection error"] }'),
    ('hint={isLoyverseSynced ? undefined : "영소문자, 숫자, 하이픈만 사용 (예: plain-bagel)"}',
     'hint={isLoyverseSynced ? undefined : "Lowercase letters, numbers, hyphens only (e.g. plain-bagel)"}'),
    ('message: `Loyverse sync Modifier의 본 필드는 Edit할 수 없습니다: ${attemptedReadOnly.join(", ")}`,',
     'message: `Loyverse-synced Modifier original fields cannot be edited: ${attemptedReadOnly.join(", ")}`,'),
    ('message: `Loyverse sync Products의 본 필드는 Edit할 수 없습니다: ${attemptedReadOnly.join(", ")}`,',
     'message: `Loyverse-synced Product original fields cannot be edited: ${attemptedReadOnly.join(", ")}`,'),
    ('note: label === "Tomorrow" ? "Predictions based 계획 수량" : null,',
     'note: label === "Tomorrow" ? "Prediction-based planned qty" : null,'),
    ('placeholder="New Password 재Enter"',
     'placeholder="Re-enter new password"'),
    ('placeholder="Order Number / Customer명 / Email"',
     'placeholder="Order Number / Customer Name / Email"'),
    ('placeholder="특별 Request사항 등"',
     'placeholder="Special requests, etc."'),
    ('placeholder="특별 Request사항을 Enter해주세요"',
     'placeholder="Enter any special requests"'),
    ('resultSummary: "ExternalFactor 이미 존재",',
     'resultSummary: "ExternalFactor already exists",'),
    ('resultSummary: "Predictions 이미 존재",',
     'resultSummary: "Prediction already exists",'),
    ('saveLabel="그룹 Add"', 'saveLabel="Add Group"'),
    ('sub="Sold량 절대 Error"', 'sub="Absolute Sales Error"'),
    ('sub="average 절대 Error"', 'sub="Average Absolute Error"'),
    ('sub="실제 Data Yes"', 'sub="Has Actual Data"'),
    ('sub={`Error율 5% 이내 · ${stats.accuracyRate}%`}',
     'sub={`Error rate ≤5% · ${stats.accuracyRate}%`}'),
    ('sub={`절대 Error ${formatCurrency(stats.avgSalesError)}`}',
     'sub={`Avg. absolute error ${formatCurrency(stats.avgSalesError)}`}'),
    ('title="Avg. Sales Error율"', 'title="Avg. Sales Error Rate"'),
    ('title="비교 Available"', 'title="Comparison Available"'),
    ('title={`Uber이츠 ${uberPercent.toFixed(1)}%`}',
     'title={`Uber Eats ${uberPercent.toFixed(1)}%`}'),
    ('{ href: "/analytics/daily", label: "📅 daily Analytics", desc: "Date별 Details" }',
     '{ href: "/analytics/daily", label: "📅 Daily Analytics", desc: "Details by date" }'),
    ('{ href: "/analytics/monthly", label: "🗓️ monthly Analytics", desc: "월간 Summary" }',
     '{ href: "/analytics/monthly", label: "🗓️ Monthly Analytics", desc: "Monthly summary" }'),
    ('{ href: "/analytics/weekly", label: "📆 Weekly Analysis", desc: "주간 트렌드" }',
     '{ href: "/analytics/weekly", label: "📆 Weekly Analysis", desc: "Weekly trends" }'),
    ('{ message: "마지막 Admin(ADMIN)의 Role을 낮출 수 없습니다" }',
     '{ message: "Cannot lower the role of the last Admin" }'),
    ('{" "}({items.length}일)',
     '{" "}({items.length} days)'),
    ('{" "}({weeks.length}주)',
     '{" "}({weeks.length} weeks)'),
    ('{customerPhone && <p><span className="text-gray-500 w-16 inline-block">전화</span>{customerPhone}</p>}',
     '{customerPhone && <p><span className="text-gray-500 w-16 inline-block">Phone</span>{customerPhone}</p>}'),
    ('{isPending ? "Processing..." : "변경"}',
     '{isPending ? "Processing..." : "Change"}'),
    ('{loading ? "Sync 중..." : "Loyverse Refresh"}',
     '{loading ? "Syncing..." : "Loyverse Refresh"}'),
    ('← Details 페이지로', '← Back to Details'),
    ('← Sales List으로', '← Back to Sales List'),
    ('← 쇼핑 계속하기', '← Continue Shopping'),
    ('✓ Done — Success {result.pushSucceeded ?? 0}items / Failed {result.pushFailed ?? 0}items / 이미 Send됨',
     '✓ Done — Success {result.pushSucceeded ?? 0} / Failed {result.pushFailed ?? 0} / Already sent'),
    ('새 Confirm Password', 'Confirm New Password'),
    ('실제 Sales Records', 'Actual Sales Records'),
    ('예: &quot;Plain Bagel&quot; Options이 베이글 Products·샌드위치 Products에 모두 사용되어도 DailyOptionInventory는 하나만 존재합니다.',
     'E.g. The &quot;Plain Bagel&quot; option used in both bagel and sandwich products has only one DailyOptionInventory entry.'),
    ('<Field label="Bagels Baked 수 *" error={errors.bagelsBaked?.message}>',
     '<Field label="Bagels Baked *" error={errors.bagelsBaked?.message}>'),
    ('<Field label="Bagels Left 수 *" error={errors.bagelsLeft?.message}>',
     '<Field label="Bagels Left *" error={errors.bagelsLeft?.message}>'),
    ('<Field label="Sort 순서" error={errors.sortOrder?.message}>',
     '<Field label="Sort Order" error={errors.sortOrder?.message}>'),
    ('<Field label="인근 Event명" error={errors.localEventName?.message}>',
     '<Field label="Local Event Name" error={errors.localEventName?.message}>'),
    ('<ResultCard title="Predicted Remaining량" value={`${prediction.predictedLeftovers}`} />',
     '<ResultCard title="Predicted Remaining" value={`${prediction.predictedLeftovers}`} />'),
    ('<StatCard label="미Send" value={notSentOrders.length} color="gray" />',
     '<StatCard label="Not Sent" value={notSentOrders.length} color="gray" />'),
    ('<StatCard label="웹 Orders (INTERNAL)" value={internalCount} color="blue" />',
     '<StatCard label="Web Orders (INTERNAL)" value={internalCount} color="blue" />'),
    ('<h1 className="text-2xl font-bold text-gray-900">External POS 연동</h1>',
     '<h1 className="text-2xl font-bold text-gray-900">External POS Integration</h1>'),
    ('<h1 className="text-2xl font-bold text-gray-900">Loyverse POS 연동</h1>',
     '<h1 className="text-2xl font-bold text-gray-900">Loyverse POS Integration</h1>'),
    ('<h1 className="text-2xl font-bold text-gray-900">Orders이 Completed되었습니다!</h1>',
     '<h1 className="text-2xl font-bold text-gray-900">Your order has been placed!</h1>'),
    ('<h1 className="text-2xl font-bold text-gray-900">Subscriptions 발생 management</h1>',
     '<h1 className="text-2xl font-bold text-gray-900">Subscription Occurrence Management</h1>'),
    ('<h1 className="text-2xl font-bold text-gray-900">새 CSV Imports</h1>',
     '<h1 className="text-2xl font-bold text-gray-900">New CSV Import</h1>'),
    ('<h1 className="text-2xl font-bold text-gray-900">새 Enter Sales</h1>',
     '<h1 className="text-2xl font-bold text-gray-900">Enter Sales</h1>'),
    ('<h1 className="text-2xl font-bold text-gray-900">새 Predictions 만들기</h1>',
     '<h1 className="text-2xl font-bold text-gray-900">Create New Prediction</h1>'),
    ('<h1 className="text-2xl font-bold text-gray-900">새 Products Add</h1>',
     '<h1 className="text-2xl font-bold text-gray-900">Add New Product</h1>'),
    ('<h1 className="text-2xl font-bold text-gray-900">장바구니</h1>',
     '<h1 className="text-2xl font-bold text-gray-900">Cart</h1>'),
    ('<h1 className="text-2xl font-bold text-gray-900">정기 Subscriptions 신청</h1>',
     '<h1 className="text-2xl font-bold text-gray-900">Subscribe to Regular Orders</h1>'),
    ('<h2 className="font-semibold text-gray-800 text-sm">Orders자 Info</h2>',
     '<h2 className="font-semibold text-gray-800 text-sm">Customer Info</h2>'),
    ('<h2 className="font-semibold text-gray-800 text-sm">Pickup 시간 (Select)</h2>',
     '<h2 className="font-semibold text-gray-800 text-sm">Pickup Time (Select)</h2>'),
    ('<h2 className="font-semibold text-gray-900 border-b border-gray-100 pb-2">Link된 Products</h2>',
     '<h2 className="font-semibold text-gray-900 border-b border-gray-100 pb-2">Linked Products</h2>'),
    ('<h2 className="font-semibold text-gray-900 text-base">Categories별 Products status</h2>',
     '<h2 className="font-semibold text-gray-900 text-base">Product Status by Category</h2>'),
    ('<h2 className="font-semibold text-gray-900">Admin 전용 Menu</h2>',
     '<h2 className="font-semibold text-gray-900">Admin Only Menu</h2>'),
    ('<h2 className="font-semibold text-gray-900">Auto Send 정책</h2>',
     '<h2 className="font-semibold text-gray-900">Auto-Send Policy</h2>'),
    ('<h2 className="font-semibold text-gray-900">Internal 운영 Settings</h2>',
     '<h2 className="font-semibold text-gray-900">Internal Operation Settings</h2>'),
    ('<h2 className="font-semibold text-gray-900">environment variable Settings 가이드</h2>',
     '<h2 className="font-semibold text-gray-900">Environment Variable Configuration Guide</h2>'),
    ('<h2 className="font-semibold text-gray-900">연동 Settings Status</h2>',
     '<h2 className="font-semibold text-gray-900">Integration Settings Status</h2>'),
    ('<h2 className="text-base font-semibold text-gray-900 border-b border-gray-100 pb-2">Local Settings (External Data Collect용)</h2>',
     '<h2 className="text-base font-semibold text-gray-900 border-b border-gray-100 pb-2">Local Settings (for External Data Collection)</h2>'),
    ('<h2 className="text-base font-semibold text-gray-900 border-b border-gray-100 pb-2">파생 지표</h2>',
     '<h2 className="text-base font-semibold text-gray-900 border-b border-gray-100 pb-2">Derived Metrics</h2>'),
    ('<h2 className="text-base font-semibold text-gray-900">Modifiers 그룹 management</h2>',
     '<h2 className="text-base font-semibold text-gray-900">Modifier Group Management</h2>'),
    ('<h2 className="text-lg font-semibold text-gray-900 mb-3">⚡ 빠른 Actions</h2>',
     '<h2 className="text-lg font-semibold text-gray-900 mb-3">⚡ Quick Actions</h2>'),
    ('<h2 className="text-lg font-semibold text-gray-900 mb-3">📊 recent 7일 실적</h2>',
     '<h2 className="text-lg font-semibold text-gray-900 mb-3">📊 Recent 7-Day Performance</h2>'),
    ('<h2 className="text-xl font-bold text-gray-800 mb-6 text-center">주요 기능</h2>',
     '<h2 className="text-xl font-bold text-gray-800 mb-6 text-center">Key Features</h2>'),
    ('<label className="text-sm font-medium text-gray-700">Status 변경</label>',
     '<label className="text-sm font-medium text-gray-700">Change Status</label>'),
    ('<p className="font-medium text-gray-700 mb-1">🔌 External POS Send (추후)</p>',
     '<p className="font-medium text-gray-700 mb-1">🔌 External POS Send (coming soon)</p>'),
    ('<p className="font-semibold mb-1">🔗 Loyverse Sync based Categories 운영</p>',
     '<p className="font-semibold mb-1">🔗 Category Management based on Loyverse Sync</p>'),
    ('<p className="font-semibold mb-2">📌 Accuracy baseline 안내</p>',
     '<p className="font-semibold mb-2">📌 Accuracy Baseline Guide</p>'),
    ('<p className="font-semibold">💡 Modifier는 공용 Inventory 단위입니다</p>',
     '<p className="font-semibold">💡 Modifiers are shared Inventory units</p>'),
    ('<p className="text-gray-500 mt-0.5 text-sm">새로운 Products Info를 Enter하세요</p>',
     '<p className="text-gray-500 mt-0.5 text-sm">Enter new product information</p>'),
    ('<p className="text-gray-500 mt-1">Bagels Beyond — Daily 운영 status을 한Snow에</p>',
     '<p className="text-gray-500 mt-1">Bagels Beyond — Daily operations status at a glance</p>'),
    ('<p className="text-gray-500 mt-1">CSV 파일을 Upload하거나, 아래에 CSV Content을 직접 붙여넣으세요.</p>',
     '<p className="text-gray-500 mt-1">Upload a CSV file or paste CSV content directly below.</p>'),
    ('<p className="text-gray-500 mt-1">Date를 Enter하면 External Factors이 automatically Collect됩니다. 필요 시 직접 Enter할 수도 있습니다.</p>',
     '<p className="text-gray-500 mt-1">External factors will be automatically collected when you enter a date. You can also enter them manually if needed.</p>'),
    ('<p className="text-gray-500 mt-1">Default Settings을 management합니다</p>',
     '<p className="text-gray-500 mt-1">Manage default settings</p>'),
    ('<p className="text-gray-500 mt-1">Every 하는 Day에 Pickup할 Products을 Subscriptions하세요</p>',
     '<p className="text-gray-500 mt-1">Subscribe to products for weekly pickup on your chosen day</p>'),
    ('<p className="text-gray-500 mt-1">daily Sales Data를 Edit합니다</p>',
     '<p className="text-gray-500 mt-1">Edit daily sales data</p>'),
    ('<p className="text-gray-500 mt-1">daily Sales Data를 Enter합니다</p>',
     '<p className="text-gray-500 mt-1">Enter daily sales data</p>'),
    ('<p className="text-gray-500 mt-1">monthly Sales 실적 및 Predictions status</p>',
     '<p className="text-gray-500 mt-1">Monthly sales performance and prediction status</p>'),
    ('<p className="text-gray-500 mt-1">계정 보안을 위해 주기적으로 Password를 변경하세요</p>',
     '<p className="text-gray-500 mt-1">Change your password regularly to keep your account secure</p>'),
    ('<p className="text-gray-500 mt-2 text-sm">Orders을 접수했습니다. Pickup Date에 visitor해주세요.</p>',
     '<p className="text-gray-500 mt-2 text-sm">Your order has been received. Please visit on your pickup date.</p>'),
    ('<p className="text-gray-500 text-sm mt-0.5">Date별 Subscriptions 발생 View 및 Orders Create (STAFF 이상)</p>',
     '<p className="text-gray-500 text-sm mt-0.5">View subscription occurrences by date and create orders (STAFF and above)</p>'),
    ('<p className="text-gray-500 text-sm mt-1">Orders 전 Content을 Confirm해주세요</p>',
     '<p className="text-gray-500 text-sm mt-1">Please check the contents before placing your order</p>'),
    ('<p className="text-gray-500 text-sm mt-1">Pickup Date와 시간을 Select하고 Orders을 Completed하세요</p>',
     '<p className="text-gray-500 text-sm mt-1">Select a pickup date and time to complete your order</p>'),
    ('<p className="text-gray-600 text-sm mb-6">Delete하시겠습니까? 이 Task은 This action cannot be undone.</p>',
     '<p className="text-gray-600 text-sm mb-6">Are you sure you want to delete? This action cannot be undone.</p>'),
    ('<p className="text-gray-600">records을 Not found.</p>',
     '<p className="text-gray-600">Record not found.</p>'),
    ('<p className="text-lg font-medium">등록된 Modifier 그룹이 없습니다</p>',
     '<p className="text-lg font-medium">No modifier groups registered</p>'),
    ('<p className="text-red-600">Valid하지 않은 Date입니다: {dateParam}</p>',
     '<p className="text-red-600">Invalid date: {dateParam}</p>'),
    ('<p className="text-xs text-gray-400">최종 Amount은 서버에서 Recalculate됩니다. 결제는 on-site에서 이루어집니다.</p>',
     '<p className="text-xs text-gray-400">Final amount will be recalculated on the server. Payment is made on-site.</p>'),
    ('<p className="text-xs text-gray-500 mt-1">최종 Amount은 서버에서 Recalculate됩니다</p>',
     '<p className="text-xs text-gray-500 mt-1">Final amount will be recalculated on the server</p>'),
    ('<span className="text-gray-600 font-medium">실제</span>',
     '<span className="text-gray-600 font-medium">Actual</span>'),
    ('<span>🕐 마지막 Send: <strong>',
     '<span>🕐 Last Sent: <strong>'),
    ('[row.productId]: "서버 Link에 Failed했습니다",',
     '[row.productId]: "Failed to connect to server",'),
    ('await addLog(taskId, `ExternalFactor Collect 예외: ${fe instanceof Error ? fe.message : String(fe)}`, "warning")',
     'await addLog(taskId, `ExternalFactor collection exception: ${fe instanceof Error ? fe.message : String(fe)}`, "warning")'),
    ('console.warn(`[weather] 온도 None | date=${dateStr} | maxTemp=${maxTemp} | minTemp=${minTemp}`)',
     'console.warn(`[weather] temperature null | date=${dateStr} | maxTemp=${maxTemp} | minTemp=${minTemp}`)'),
    ('data: { scheduledTaskId: task.id, message: `ExternalFactor 이미 존재: ${toDateKey(d)}`, level: "info" }',
     'data: { scheduledTaskId: task.id, message: `ExternalFactor already exists: ${toDateKey(d)}`, level: "info" }'),
    ('data: { scheduledTaskId: task.id, message: `Predictions 이미 존재: ${toDateKey(d)}`, level: "info" }',
     'data: { scheduledTaskId: task.id, message: `Prediction already exists: ${toDateKey(d)}`, level: "info" }'),
    ('data: { status: "invalid", validationErrors: "Date Info가 없습니다" }',
     'data: { status: "invalid", validationErrors: "Date information is missing" }'),
    ('description="Factor별 Sales Predictions Weights를 management합니다"',
     'description="Manage sales prediction weights by factor"'),
    ('errorMessage: "Data 부족: recent records None"',
     'errorMessage: "Insufficient data: no recent records"'),
    ('errorMessage: err instanceof Error ? err.message : "알 수 없는 Error"',
     'errorMessage: err instanceof Error ? err.message : "Unknown error"'),
    ('notes: `baseline Data: recent 30일 | same-day 4items reference | Applied Factor: 1`',
     'notes: `Baseline data: recent 30 days | same-day 4 data points reference | Applied Factor: 1`'),
    ('resultSummary: "대상: 1일 | Processing: 1일 | Failed provider: news"',
     'resultSummary: "Target: 1 day | Processed: 1 day | Failed provider: news"'),
    ('resultSummary: "대상: 1일 | Processing: 1일"',
     'resultSummary: "Target: 1 day | Processed: 1 day"'),
    ('setErrorMsg(data.error ?? "알 수 없는 Error")',
     'setErrorMsg(data.error ?? "Unknown error")'),
    ('setFeedback((f) => ({ ...f, [product.id]: `"${group.name}" Options을 Please select` }))',
     'setFeedback((f) => ({ ...f, [product.id]: `Please select "${group.name}" option` }))'),
    ('setFetchError(data.message ?? "Inventory Info를 loading Failed했습니다")',
     'setFetchError(data.message ?? "Failed to load inventory info")'),
    ('setMessage("재Send Success")', 'setMessage("Re-send successful")'),
    ('setMessage(data.result?.error ?? data.error ?? "재Send Failed")',
     'setMessage(data.result?.error ?? data.error ?? "Re-send failed")'),
    ('setMessage({ type: "error", text: data.message ?? "Processing에 Failed했습니다" })',
     'setMessage({ type: "error", text: data.message ?? "Processing failed" })'),
    ('setMessage({ type: "success", text: "Status가 변경되었습니다" })',
     'setMessage({ type: "success", text: "Status changed" })'),
    ('setMessage({ type: "success", text: "변경사항이 Save되었습니다" })',
     'setMessage({ type: "success", text: "Changes saved" })'),
    ('throw new Error(data.error ?? "Retry에 Failed했습니다")',
     'throw new Error(data.error ?? "Retry failed")'),
    ('throw new Error(err.message || "Create에 Failed했습니다")',
     'throw new Error(err.message || "Create failed")'),
    ('throw new Error(err.message || "Link에 Failed했습니다")',
     'throw new Error(err.message || "Link failed")'),
    ('throw new Error(err.message || "Remove에 Failed했습니다")',
     'throw new Error(err.message || "Remove failed")'),
    ('title={`Orders ${orderNumber} 재Send`}',
     'title={`Re-send Order ${orderNumber}`}'),
    # Remaining that may show up
    ('이미 사용 중인 slug입니다', 'Slug is already in use'),
    ('자기 자신을 cannot be deactivated', 'You cannot deactivate yourself'),
    ('마지막 Active Admin(ADMIN)는 cannot be deactivated', 'The last active Admin cannot be deactivated'),
    ('자기 자신의 Role을 ADMIN 아래로 낮출 수 없습니다', 'You cannot lower your own role below ADMIN'),
    # Service patterns
    ('이미 존재', 'already exists'),
    ('이미 존재:', 'already exists:'),
    # Remaining misc
    ('Inventory 추적', 'Inventory Tracking'),
    ('실적', 'performance'),
    ('발생', 'occurrence'),
    ('연동', 'integration'),
    ('운영', 'operation'),
    ('설치', 'installation'),
    ('한Snow에', 'at a glance'),
]

def process_file(filepath: str) -> bool:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except (UnicodeDecodeError, IOError):
        return False
    
    original = content
    
    for old, new in FIXES:
        content = content.replace(old, new)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False


def main():
    result = subprocess.run(
        ["find", PROJECT_ROOT, "-type", "f", "(", "-name", "*.ts", "-o", "-name", "*.tsx", ")"],
        capture_output=True, text=True
    )
    all_files = [f for f in result.stdout.strip().split('\n') 
                 if f and 'node_modules' not in f and '.next' not in f and 'scripts/' not in f]
    
    import re
    changed = 0
    for filepath in all_files:
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            if not re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', content):
                continue
        except (UnicodeDecodeError, IOError):
            continue
        
        if process_file(filepath):
            rel = filepath.replace(PROJECT_ROOT + '/', '')
            print(f"  FIXED: {rel}")
            changed += 1
    
    print(f"\nTotal fixed: {changed} files")


if __name__ == "__main__":
    main()
