#!/usr/bin/env python3
"""Replace all Korean text with English equivalents across the project."""

import os
import re
import sys

# Order matters: longer/more specific strings first to avoid partial replacements
REPLACEMENTS = [
    # Long sentences / full phrases first
    ("매출 기록부터 예측, 생산량 추천까지 — 베이글 매장 운영을 스마트하게", "From sales records to predictions and production recommendations — manage your bagel shop smartly"),
    ("신선한 베이글을 예약 픽업 주문하세요. 결제는 현장에서 이루어집니다.", "Order fresh bagels for scheduled pickup. Payment is made on-site."),
    ("날짜를 변경하면 해당 날짜의 재고 현황이 자동으로 불러와집니다", "Changing the date will automatically load inventory for that date."),
    ("날짜별 상품 생산량 및 재고 현황을 관리합니다", "Manage daily product production and inventory status"),
    ("이 페이지에 접근할 권한이 없습니다", "You do not have permission to access this page."),
    ("자동 전송 대상이지만 아직 전송 시도가 없는 주문입니다", "Orders targeted for auto-send but not yet attempted."),
    ("오늘({date}) 픽업 예정 주문의 Loyverse 자동 전송 상태", "Loyverse auto-send status for today's ({date}) scheduled pickup orders"),
    ("주문 전송 전에 모든 옵션이 매핑되어 있어야 합니다", "All options must be mapped before sending orders."),
    ("외부 POS 시스템과의 카탈로그 동기화를 관리합니다", "Manage catalog synchronization with external POS systems."),
    ("카테고리·모디파이어 그룹·옵션·상품을 한 번에 동기화합니다", "Sync categories, modifier groups, options, and products all at once."),
    ("카테고리 → 모디파이어 그룹/옵션 → 상품 → 연결 관계를 한 번에 동기화합니다", "Syncs categories → modifier groups/options → products → links all at once."),
    ("메뉴 카탈로그, 상품, 모디파이어 동기화", "Sync menu catalog, products, and modifiers"),
    ("상품과 모디파이어 그룹의 연결 관계도 같이 업데이트됩니다", "Product-modifier group links are also updated."),
    ("모디파이어 그룹과 옵션을 생성·수정하고, 상품에서 연결할 수 있습니다", "Create and edit modifier groups and options, and link them to products."),
    ("전체 상품 목록 및 가격·활성 상태를 관리합니다", "Manage the full product list, prices, and active status."),
    ("이 상품에 연결된 모디파이어 그룹 목록입니다", "List of modifier groups linked to this product."),
    ("이 상품은 Loyverse에서 동기화된 데이터입니다. 원본 필드(이름, 슬러그, 설명, 기본가격)는 수정할 수 없으며 내부 운영 필드만 수정 가능합니다.", "This product is synced from Loyverse. Original fields (name, slug, description, base price) cannot be edited. Only internal operation fields can be modified."),
    ("✏️ 내부 운영 필드 (수정 가능)", "✏️ Internal Operation Fields (Editable)"),
    ("🔒 Loyverse 원본 (수정 불가)", "🔒 Loyverse Original (Read-only)"),
    ("위의 + 그룹 연결 버튼으로 기존 그룹을 연결하거나", "Use the + Link Group button above to link an existing group, or"),
    ("에서 그룹·옵션을 생성하거나 수정할 수 있습니다", "to create or edit groups and options."),
    ("에서 새 그룹을 만드세요", "Create a new group there."),
    ("모디파이어 관리에서 새 그룹 만들기", "Create new group in Modifier Management"),
    ("아래 테이블의 \"Loyverse Modifier\" 열에서 modifier option ID를 직접 입력할 수", "You can directly enter the modifier option ID in the \"Loyverse Modifier\" column in the table below"),
    ("있습니다. Loyverse 동기화가 성공하면 이 모드를 닫고 드롭다운에서 선택하세요", "After successful Loyverse sync, close this mode and select from the dropdown."),
    ("조건별 매출 및 운영 지표 비교", "Compare sales and operational metrics by condition"),
    ("⚠ 실제 토큰은 절대 소스 코드나 저장소에 커밋하지 마세요", "⚠ Never commit actual tokens to source code or a repository."),
    ("실제 API 연동을 위해 LOYVERSE_API_TOKEN 환경변수를 설정하세요", "Set the LOYVERSE_API_TOKEN environment variable for live integration."),
    ("Loyverse sync된 옵션은 삭제할 수 없습니다", "Cannot delete Loyverse-synced options"),
    ("Loyverse sync된 옵션은 수정할 수 없습니다", "Cannot edit Loyverse-synced options"),
    ("Loyverse sync된 그룹은 삭제할 수 없습니다", "Cannot delete Loyverse-synced groups"),
    ("Loyverse sync된 그룹은 수정할 수 없습니다", "Cannot edit Loyverse-synced groups"),
    ("베이글 종류(Bagel Type)는 variant가 아닌 modifier 기준으로 관리됩니다", "Bagel types (Bagel Type) are managed by modifier, not variant."),
    ('예: "Plain Bagel" 옵션이 베이글 상품·샌드위치 상품에 모두 사용되어도 DailyOptionInventory는 하나만 존재합니다', 'E.g. The "Plain Bagel" option used in both bagel and sandwich products only has one DailyOptionInventory entry.'),
    ("일반적으로 -1.0 ~ +1.0 범위 권장", "Typically recommended range: -1.0 ~ +1.0"),
    ("기본 폐기 허용 비율 (0~1)", "Default Waste Allowance (0~1)"),
    ("계정이 없으신가요?", "Don't have an account?"),
    ("이미 계정이 있으신가요?", "Already have an account?"),
    ("분석 데이터가 없습니다", "No analytics data."),
    ("해당 기간에 데이터가 없습니다", "No data for this period."),
    ("해당 세그먼트의 데이터가 없습니다", "No data for this segment."),
    ("해당 카테고리의 가중치가 없습니다", "No weights for this category."),
    ("등록된 상품이 없습니다. 먼저 상품을 추가해주세요.", "No products registered. Please add a product first."),
    ("등록된 모디파이어 그룹이 없습니다. 그룹을 추가해보세요.", "No modifier groups registered. Try adding a group."),
    ("이 카테고리에 상품이 없습니다", "No products in this category"),
    ("✅ 설정이 저장되었습니다", "✅ Settings saved."),
    ("✅ 수집 완료", "✅ Collection complete"),
    ("✅ 저장되었습니다. 목록 페이지로 이동합니다...", "✅ Saved. Redirecting to list page..."),
    ("✅ 저장되었습니다. 상품 목록으로 이동합니다...", "✅ Saved. Redirecting to products list..."),
    ("✓ 동기화 완료", "✓ Sync complete"),
    ("✓ 설정됨", "✓ Configured"),
    ("✓ 완료", "✓ Done"),
    ("✗ 미설정 (LOYVERSE_API_TOKEN)", "✗ Not configured (LOYVERSE_API_TOKEN)"),
    ("오늘 데이터 보기/수집", "View/Collect Today's Data"),
    ("오늘 재고 현황", "Today's Inventory"),
    ("실제 API 연동", "Live API Integration"),
    ("기준 타임존", "Base Timezone"),
    ("향후 자동 계산", "Auto-calculated in the future"),
    ("안녕하세요, {name}님 ({role})", "Hello, {name} ({role})"),
    ("베이글스 비욘드", "Bagels Beyond"),
    ("미전송 주문", "Unsent Orders"),
    ("엑셀이나 스프레드시트에서 복사한 CSV 텍스트를 여기에 붙여넣을 수 있습니다", "You can paste CSV text copied from Excel or a spreadsheet here."),
    ("같은 날짜가 있으면 덮어쓰기 (기본: 건너뜀)", "Overwrite if date exists (default: skip)"),
    ("첫 번째 CSV 파일 업로드", "Upload First CSV File"),
    ("첫 번째 매출 입력하기", "Enter First Sales Record"),
    ("첫 번째 예측 만들기", "Create First Prediction"),
    ("🔮 내일 예측 만들기", "🔮 Create Tomorrow's Prediction"),
    ("필수 선택 그룹", "Required Selection Group"),
    ("▶ 버튼을 클릭하거나 행을 클릭하면 하위 옵션 목록이 펼쳐집니다", "▶ Click the button or row to expand the option list."),
    ("📊 성과 보기", "📊 View Performance"),
    ("📥 템플릿 다운로드", "📥 Download Template"),
    ("오늘({date}) 픽업 예정 주문의 Loyverse 자동 전송 상태", "Loyverse auto-send status for today's ({date}) scheduled pickup orders"),
    ("공휴일명", "Holiday Name"),
    ("예측 상세 — {date}", "Prediction Details — {date}"),
    ("구독 플랜 관리", "Subscription Plan Management"),
    ("주문 자동 전송 현황", "Order Auto-Send Status"),
    ("관리자 대시보드", "Admin Dashboard"),
    ("운영 대시보드", "Operations Dashboard"),
    ("매출 분석", "Sales Analytics"),
    ("요일별 분석", "Day-of-Week Analysis"),
    ("매출 예측", "Sales Predictions"),
    ("가중치 관리", "Weights Management"),
    ("성과 분석", "Performance Analysis"),
    ("상품 관리", "Product Management"),
    ("모디파이어 관리", "Modifier Management"),
    ("카테고리 관리", "Category Management"),
    ("재고 관리", "Inventory Management"),
    ("사용자 관리", "Users"),
    ("주문 관리", "Order Management"),
    ("구독 관리", "Manage Subscriptions"),
    ("매출 입력", "Enter Sales"),
    ("매출 목록", "Sales List"),
    ("매출 기록 보기", "View Sales Records"),
    ("매출 입력하기", "Enter Sales"),
    ("매출 기록", "Sales Records"),
    ("고객 메뉴", "Customer Menu"),
    ("내 계정", "My Account"),
    ("메뉴 / 주문", "Menu / Order"),
    ("내 주문 보기", "View My Orders"),
    ("내 주문", "My Orders"),
    ("구독 신청하기", "Subscribe"),
    ("구독 추가", "Add Subscription"),
    ("상품 목록으로 돌아가기", "Back to Products"),
    ("상품 보러 가기", "Browse Products"),
    ("주문하러 가기", "Place an Order"),
    ("로그인하러 가기", "Go to Login"),
    ("계속 쇼핑하기", "Continue Shopping"),
    ("장바구니 보기", "View Cart"),
    ("결제하기", "Checkout"),
    ("새 가져오기", "New Import"),
    ("비밀번호 확인", "Confirm Password"),
    ("현재 비밀번호", "Current Password"),
    ("새 비밀번호 확인", "Confirm New Password"),
    ("새 비밀번호", "New Password"),
    ("기간 비교", "Period Comparison"),
    ("실적 + 예측 모두 있음", "Has both actual and predicted"),
    ("실제 매출 기록", "Actual Sales Record"),
    ("예측만 있음", "Prediction only"),
    ("예측 있음", "Has Prediction"),
    ("실제 매출", "Actual Sales"),
    ("실제 베이글", "Actual Bagels"),
    ("예측 베이글", "Predicted Bagels"),
    ("예상 매출", "Predicted Sales"),
    ("예측 매출", "Predicted Sales"),
    ("추천 생산량", "Recommended Production"),
    ("생산 추천", "Recommended Production"),
    ("이번 달 기록", "This Month Records"),
    ("이번 달 매출", "This Month Sales"),
    ("일평균 매출", "Daily Avg. Sales"),
    ("지난 달 매출", "Last Month Sales"),
    ("총 매출", "Total Sales"),
    ("총매출", "Total Sales"),
    ("평균 폐기율", "Avg. Waste Rate"),
    ("주별 분석", "Weekly Analysis"),
    ("전체 기간", "Full Period"),
    ("베이글 생산", "Bagels Baked"),
    ("구운 베이글", "Bagels Baked"),
    ("베이글 판매수량", "Bagels Sold"),
    ("베이글 판매", "Bagels Sold"),
    ("남은 베이글", "Bagels Left"),
    ("외부 요인", "External Factors"),
    ("학교 방학", "School Holiday"),
    ("학교방학", "School Holiday"),
    ("뉴질랜드 뉴스", "NZ News"),
    ("세계 뉴스", "World News"),
    ("국제 뉴스", "World News"),
    ("동기화 완료", "Sync Complete"),
    ("저장 중…", "Saving..."),
    ("저장 중", "Saving..."),
    ("✓ 저장됨", "✓ Saved"),
    ("저장됨", "Saved"),
    ("삭제 중", "Deleting..."),
    ("연결 중", "Connecting..."),
    ("처리 중…", "Processing..."),
    ("처리 중", "Processing..."),
    ("제거 중", "Removing..."),
    ("비밀번호", "Password"),
    ("회원가입", "Sign Up"),
    ("로그인", "Login"),
    ("프로필 수정", "Edit Profile"),
    ("일시정지", "Pause"),
    ("주문 취소", "Cancel Order"),
    ("권한 변경", "Change Role"),
    ("매핑 관리", "Manage Mapping"),
    ("외부 데이터 상세", "External Data Details"),
    ("분석 상세", "Analytics Details"),
    ("성과 상세", "Performance Details"),
    ("예측 상세", "Prediction Details"),
    ("기록 보기", "View Records"),
    ("성과 보기", "View Performance"),
    ("상세 보기", "View Details"),
    ("세그먼트 상세", "Segment Details"),
    ("전체 보기", "View All"),
    ("매핑 저장", "Save Mapping"),
    ("Loyverse modifier 선택", "Select Loyverse modifier"),
    ("Loyverse modifier option ID 입력", "Enter Loyverse modifier option ID"),
    ("+ 옵션 추가", "+ Add Option"),
    ("매주 {day}요일", "Every {day}"),
    ("픽업: {date}", "Pickup: {date}"),
    ("오류: {msg}", "Error: {msg}"),
    ("오류: {message}", "Error: {message}"),
    ("{name}의 권한 변경", "Change {name}'s role"),
    ("{name} 비활성화", "Deactivate {name}"),
    ("{name} 활성화", "Activate {name}"),
    ("* 필수", "* Required"),
    ("오늘({date})", "Today ({date})"),
    ("조회 날짜", "Query Date"),
    ("기록 보기 →", "View Records →"),
    ("상세 →", "Details →"),
    ("수정 →", "Edit →"),
    ("외부 데이터 상세 →", "External Data Details →"),
    ("분석 상세 →", "Analytics Details →"),
    ("성과 상세 →", "Performance Details →"),
    ("매핑 관리 →", "Manage Mapping →"),
    ("목록으로", "Back to List"),
    ("돌아가기", "Back"),
    ("재계산", "Recalculate"),
    ("활성화", "Activate"),
    ("비활성화", "Deactivate"),
    ("초기화", "Reset"),
    ("파일 선택", "Select File"),
    ("건너뛰기", "Skip"),
    ("미리보기", "Preview"),
    ("구독 가능", "Subscribable"),
    ("재고추적", "Inventory Tracking"),
    ("✓ 매핑됨", "✓ Mapped"),
    ("✗ 미매핑", "✗ Unmapped"),
    ("매핑됨", "Mapped"),
    ("미매핑 없음", "No unmapped"),
    ("미매핑", "Unmapped"),
    ("품절", "Out of Stock"),
    ("선택 안 함", "No selection"),
    ("선택해주세요", "Please select"),
    ("옵션이 없습니다", "No options"),
    ("데이터 없음", "No Data"),
    ("날짜 없음", "No Date"),
    ("✓ 있음", "✓ Yes"),
    ("✗ 없음", "✗ None"),
    ("있음", "Yes"),
    ("없음", "None"),
    ("아니오", "No"),
    ("오늘", "Today"),
    ("실패:", "Failed:"),
    ("이 날짜의 실제 매출 기록이 없습니다", "No actual sales record for this date."),
    ("픽업:", "Pickup:"),
    ("방식:", "Method:"),
    ("생성:", "Created:"),
    ("매주", "Every"),
    ("Cache 사용: 아니오", "Cache used: No"),
    ("Fallback 사용: 아니오", "Fallback used: No"),
    ("Mock 모드", "Mock mode"),
    ("HTTP 상태", "HTTP status"),
    ("원문에 \"modifier_ids\" 포함", 'original contains "modifier_ids"'),
    ("요청 URL", "Request URL"),
    ("링크 생성 성공", "link creation success"),
    ("링크 생성 실패", "link creation failed"),
    ("modifier 매칭 실패", "modifier matching failed"),
    ("modifier_ids 빈 배열", "modifier_ids empty array"),
    ("modifier_ids 없음", "modifier_ids missing"),
    ("modifier_ids 있음", "modifier_ids present"),
    ("modifier_ids 필드 없음", "modifier_ids field absent"),
    ("예시 헤더", "Example header"),
    ("선택 컬럼", "Optional columns"),
    # Dynamic count patterns
    ("검색 결과 {n}개 그룹", "{n} groups found"),
    ("검색 결과 {n}개", "{n} results"),
    ("검색 결과 {n}명", "{n} users found"),
    ("전체 {n}개 그룹", "{n} groups total"),
    ("전체 {n}개 상품", "{n} products total"),
    ("전체 {n}명", "{n} users total"),
    ("활성 {n}개", "{n} active"),
    ("상품 {n}개", "{n} products"),
    ("신뢰도 {n}%", "Confidence {n}%"),
    ("일평균 {amount}", "Daily Avg. {amount}"),
    ("잔여 {n}개", "Remaining: {n}"),
    ("판매 {n}개", "Sold: {n}"),
    ("폐기율 {n}%", "Waste Rate: {n}%"),
    ("베이글 {n}개", "{n} bagels"),
    ("생산 추천 {n}개", "Recommended Production: {n}"),
    ("오류 {n}건", "Errors: {n}"),
    ("실패 {providers}", "Failed: {providers}"),
    ("🔗 Loyverse {n}개", "🔗 Loyverse {n}"),
    ("그룹 {n}개", "{n} groups"),
    ("옵션 {n}개", "{n} options"),
    ("모디파이어 그룹 {n}개 · 옵션 {m}개", "{n} modifier groups · {m} options"),
    ("상품-모디파이어 연결 {n}건", "Product-modifier links: {n}"),
    ("제거된 stale 링크 {n}건", "Stale links removed: {n}"),
    ("가져옴 {n}개 · 신규 {m}개 · 업데이트 {k}개", "Fetched {n} · New {m} · Updated {k}"),
    ("성공 {n}건 / 실패 {m}건 / 이미 전송됨", "Success {n} / Failed {m} / Already sent"),
    ("처리 {n}건", "Processed {n}"),
    ("대상 날짜 {n}건", "Target dates: {n}"),
    ("실패 {n}건", "Failed: {n}"),
    ("총 {n}행 · 유효 {m}행", "Total {n} rows · Valid {m} rows"),
    ("총 {n}행 · 성공 {m} · 실패 {k}", "Total {n} rows · Success {m} · Failed {k}"),
    ("선택 {min}~{max}개 · {n}개 옵션", "Select {min}~{max} · {n} options"),
    ("선택 {min}~{max}개", "Select {min}~{max}"),
    ("개 옵션", " options"),
    ("매장매출", "Store Sales"),
    ("우버매출", "Uber Sales"),
    ("도어대쉬매출", "DoorDash Sales"),
    ("매출", "Sales"),
    ("도어대쉬", "DoorDash"),
    ("우버", "Uber"),
    ("매장", "Store"),
    ("픽업", "Pickup"),
    # Korean navigation / menu terms
    ("주문하기", "Order"),
    ("구독", "Subscriptions"),
    ("홈", "Home"),
    ("메뉴", "Menu"),
    ("대시보드", "Dashboard"),
    ("분석", "Analytics"),
    ("달력", "Calendar"),
    ("재고", "Inventory"),
    ("제품", "Products"),
    ("상품", "Products"),
    ("모디파이어", "Modifiers"),
    ("카테고리", "Categories"),
    ("주문", "Orders"),
    ("예측", "Predictions"),
    ("가중치", "Weights"),
    ("가져오기", "Imports"),
    ("외부 데이터", "External Data"),
    ("자동화", "Automation"),
    ("외부 연동", "Integrations"),
    ("사용자", "Users"),
    ("관리자", "Admin"),
    ("설정", "Settings"),
    # Field / label terms
    ("이름", "Name"),
    ("이메일", "Email"),
    ("날짜", "Date"),
    ("상태", "Status"),
    ("소스", "Source"),
    ("실패 이유", "Failure Reason"),
    ("외부 수신번호", "External Ref"),
    ("주문번호", "Order Number"),
    ("픽업 시간대", "Pickup Time"),
    ("전송 시각", "Sent At"),
    ("비고", "Notes"),
    ("계획수량", "Planned Qty"),
    ("생산수량", "Production Qty"),
    ("판매수량", "Sold Qty"),
    ("예약수량", "Reserved Qty"),
    ("전체", "All"),
    ("기타", "Other"),
    ("기간", "Period"),
    ("방식", "Method"),
    ("오차", "Error"),
    ("신뢰도", "Confidence"),
    ("정확도", "Accuracy"),
    ("일평균", "Daily Avg."),
    ("폐기율", "Waste Rate"),
    ("잔여", "Remaining"),
    ("판매", "Sold"),
    ("행", "Rows"),
    ("건", "items"),
    ("주말", "Weekend"),
    ("공휴일", "Holiday"),
    ("이벤트", "Event"),
    ("방학", "School Holiday"),
    ("날씨", "Weather"),
    ("동기화", "Sync"),
    ("저장", "Save"),
    ("삭제", "Delete"),
    ("수정", "Edit"),
    ("생성", "Create"),
    ("취소", "Cancel"),
    ("상세", "Details"),
    ("목록", "List"),
    ("검색", "Search"),
    ("필터", "Filter"),
    ("조회", "View"),
    ("닫기", "Close"),
    ("확인", "Confirm"),
    ("추가", "Add"),
    ("제거", "Remove"),
    ("연결", "Link"),
    ("활성", "Active"),
    ("비활성", "Inactive"),
    ("가능", "Available"),
    ("불가", "Unavailable"),
    ("무료", "Free"),
    ("필수", "Required"),
    ("선택 사항", "Optional"),
    ("내부", "Internal"),
    ("기본가격", "base price"),
    ("성과", "Performance"),
    ("개월", "months"),
    ("대쉬", "Dash"),
    ("안녕하세요", "Hello"),
    # API response messages
    ("저장되었습니다", "Saved"),
    ("생성되었습니다", "Created"),
    ("삭제되었습니다", "Deleted"),
    ("수정되었습니다", "Updated"),
    ("찾을 수 없습니다", "Not found"),
    ("권한이 없습니다", "Unauthorized"),
    ("잘못된 요청입니다", "Bad request"),
    ("서버 오류", "Server error"),
    ("이미 존재합니다", "Already exists"),
    ("필수 항목입니다", "Required field"),
    # Remaining small units / suffixes
    ("나) ", "Me) "),
    ("(나)", "(Me)"),
    ("(자동)", "(Auto)"),
    ("님", ""),
    # Compound terms that may remain after individual replacements
    ("주문 / 구독", "Orders / Subscriptions"),
    ("상품 / 재고", "Products / Inventory"),
    ("분석 / 예측", "Analytics / Predictions"),
    ("데이터", "Data"),
]

# Regex-based replacements for dynamic patterns in actual code
REGEX_REPLACEMENTS = [
    # pastedCsvText template literal
    (r'미리보기\$\{pastedCsvText\.trim\(\) \? " \(붙여넣기 내용\)" : " \(업로드 파일\)"\}',
     'Preview${pastedCsvText.trim() ? " (pasted content)" : " (uploaded file)"}'),
    (r'미리보기\$\{[^}]+\}',
     lambda m: m.group(0).replace("미리보기", "Preview")),
    # 매주 {day}요일 in template literals
    (r'매주 \$\{([^}]+)\}요일', r'Every ${\1}'),
    # 🔗 Loyverse dynamic count
    (r'🔗 Loyverse \$\{([^}]+)\}개', r'🔗 Loyverse ${\1}'),
    # Dynamic count patterns in template literals
    (r'그룹 \$\{([^}]+)\}개', r'${\1} groups'),
    (r'옵션 \$\{([^}]+)\}개', r'${\1} options'),
    (r'모디파이어 그룹 \$\{([^}]+)\}개 · 옵션 \$\{([^}]+)\}개', r'${\1} modifier groups · ${\2} options'),
    (r'상품-모디파이어 연결 \$\{([^}]+)\}건', r'Product-modifier links: ${\1}'),
    (r'제거된 stale 링크 \$\{([^}]+)\}건', r'Stale links removed: ${\1}'),
    (r'가져옴 \$\{([^}]+)\}개 · 신규 \$\{([^}]+)\}개 · 업데이트 \$\{([^}]+)\}개', r'Fetched ${\1} · New ${\2} · Updated ${\3}'),
    (r'성공 \$\{([^}]+)\}건 / 실패 \$\{([^}]+)\}건 / 이미 전송됨', r'Success ${\1} / Failed ${\2} / Already sent'),
    (r'처리 \$\{([^}]+)\}건', r'Processed ${\1}'),
    (r'대상 날짜 \$\{([^}]+)\}건', r'Target dates: ${\1}'),
    (r'실패 \$\{([^}]+)\}건', r'Failed: ${\1}'),
    (r'총 \$\{([^}]+)\}행 · 유효 \$\{([^}]+)\}행', r'Total ${\1} rows · Valid ${\2} rows'),
    (r'총 \$\{([^}]+)\}행 · 성공 \$\{([^}]+)\} · 실패 \$\{([^}]+)\}', r'Total ${\1} rows · Success ${\2} · Failed ${\3}'),
    (r'검색 결과 \$\{([^}]+)\}개 그룹', r'${\1} groups found'),
    (r'검색 결과 \$\{([^}]+)\}개', r'${\1} results'),
    (r'검색 결과 \$\{([^}]+)\}명', r'${\1} users found'),
    (r'전체 \$\{([^}]+)\}개 그룹', r'${\1} groups total'),
    (r'전체 \$\{([^}]+)\}개 상품', r'${\1} products total'),
    (r'전체 \$\{([^}]+)\}명', r'${\1} users total'),
    (r'활성 \$\{([^}]+)\}개', r'${\1} active'),
    (r'상품 \$\{([^}]+)\}개', r'${\1} products'),
    (r'신뢰도 \$\{([^}]+)\}%', r'Confidence ${\1}%'),
    (r'일평균 \$\{([^}]+)\}', r'Daily Avg. ${\1}'),
    (r'잔여 \$\{([^}]+)\}개', r'Remaining: ${\1}'),
    (r'판매 \$\{([^}]+)\}개', r'Sold: ${\1}'),
    (r'폐기율 \$\{([^}]+)\}%', r'Waste Rate: ${\1}%'),
    (r'베이글 \$\{([^}]+)\}개', r'${\1} bagels'),
    (r'생산 추천 \$\{([^}]+)\}개', r'Recommended Production: ${\1}'),
    (r'오류 \$\{([^}]+)\}건', r'Errors: ${\1}'),
    (r'실패 \$\{([^}]+)\}', r'Failed: ${\1}'),
    (r'🔗 Loyverse \$\{([^}]+)\}개', r'🔗 Loyverse ${\1}'),
    (r'선택 \$\{([^}]+)\}~\$\{([^}]+)\}개 · \$\{([^}]+)\}개 옵션', r'Select ${\1}~${\2} · ${\3} options'),
    (r'선택 \$\{([^}]+)\}~\$\{([^}]+)\}개', r'Select ${\1}~${\2}'),
    (r'\$\{([^}]+)\}개 옵션', r'${\1} options'),
    (r'오류: \$\{([^}]+)\}', r'Error: ${\1}'),
    # name/honorifics in template strings
    (r'안녕하세요,?\s*\$\{([^}]+)\}님\s*\(\$\{([^}]+)\}\)', r'Hello, ${\1} (${\2})'),
    (r'\$\{([^}]+)\}의 권한 변경', r"Change ${\1}'s role"),
    (r'\$\{([^}]+)\} 비활성화', r'Deactivate ${\1}'),
    (r'\$\{([^}]+)\} 활성화', r'Activate ${\1}'),
    (r'픽업: \$\{([^}]+)\}', r'Pickup: ${\1}'),
    (r'오늘\(\$\{([^}]+)\}\) 픽업 예정 주문의 Loyverse 자동 전송 상태', r"Loyverse auto-send status for today's (${\1}) scheduled pickup orders"),
    # 매주 {day}
    (r'매주 \$\{([^}]+)\}', r'Every ${\1}'),
    (r'매주 ([월화수목금토일])', r'Every \1'),
    # Rain patterns
    (r'비 \$\{([^}]+)\}mm', r'Rain ${\1}mm'),
    # 미리보기 template literal
    (r'미리보기\$\{([^}]+)\}', r'Preview${\1}'),
    # {name}님 honorific
    (r'\$\{([^}]+)\}님', r'${\1}'),
]

def process_file(filepath: str) -> tuple[bool, int]:
    """Process a single file, returning (changed, count)."""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except (UnicodeDecodeError, IOError) as e:
        print(f"  ERROR reading {filepath}: {e}")
        return False, 0

    original = content

    # Apply regex replacements first (more specific)
    for pattern, replacement in REGEX_REPLACEMENTS:
        if callable(replacement):
            content = re.sub(pattern, replacement, content)
        else:
            content = re.sub(pattern, replacement, content)

    # Apply literal replacements
    for korean, english in REPLACEMENTS:
        content = content.replace(korean, english)

    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True, 1
    return False, 0


def main():
    project_root = "/home/runner/work/Beyond/Beyond"

    # Files specified in the task
    target_files = [
        "lib/config/navigation.ts",
        "components/TaskActionButton.tsx",
        "components/WeightsManager.tsx",
        "components/Navigation.tsx",
        "components/DeletePredictionButton.tsx",
        "components/CalendarView.tsx",
        "components/FilterBar.tsx",
        "components/CollectExternalButton.tsx",
        "components/DeleteRecordButton.tsx",
        "components/analytics/PeriodComparisonSection.tsx",
        "components/analytics/DayOfWeekTable.tsx",
        "components/analytics/ComparisonCard.tsx",
        "components/analytics/AnalyticsSubNav.tsx",
        "components/analytics/ChannelBar.tsx",
        "components/navigation/Sidebar.tsx",
        "components/navigation/MobileDrawer.tsx",
        "components/RetryTaskButton.tsx",
        "components/ConfirmDeleteDialog.tsx",
        "components/RefreshExternalFactorButton.tsx",
        "components/SettingsForm.tsx",
        "components/SalesForm.tsx",
        "app/admin/products/ProductForm.tsx",
        "app/admin/products/new/page.tsx",
        "app/admin/products/page.tsx",
        "app/admin/products/[id]/OptionGroupManager.tsx",
        "app/admin/products/[id]/page.tsx",
        "app/admin/products/[id]/DeleteProductButton.tsx",
        "app/admin/products/ProductFilters.tsx",
        "app/admin/categories/CatalogSyncButton.tsx",
        "app/admin/categories/page.tsx",
        "app/admin/integrations/page.tsx",
        "app/admin/integrations/loyverse/LoyverseSyncButton.tsx",
        "app/admin/integrations/loyverse/page.tsx",
        "app/admin/integrations/loyverse/modifiers/ModifierMappingManager.tsx",
        "app/admin/integrations/loyverse/modifiers/page.tsx",
        "app/admin/sync/orders/RetryButton.tsx",
        "app/admin/sync/orders/page.tsx",
        "app/admin/sync/orders/RunSyncButton.tsx",
        "app/admin/orders/[orderNumber]/page.tsx",
        "app/admin/orders/[orderNumber]/OrderStatusChanger.tsx",
        "app/admin/orders/page.tsx",
        "app/admin/page.tsx",
        "app/admin/users/UserFilters.tsx",
        "app/admin/users/UserTable.tsx",
        "app/admin/users/page.tsx",
        "app/admin/subscriptions/page.tsx",
        "app/admin/subscriptions/[id]/AdminSubscriptionStatusForm.tsx",
        "app/admin/subscriptions/[id]/page.tsx",
        "app/admin/inventory/InventoryManager.tsx",
        "app/admin/inventory/page.tsx",
        "app/admin/subscription-occurrences/OccurrencesAdminActions.tsx",
        "app/admin/subscription-occurrences/page.tsx",
        "app/admin/modifiers/ModifierFilters.tsx",
        "app/admin/modifiers/ModifierGroupList.tsx",
        "app/admin/modifiers/ModifierSyncButton.tsx",
        "app/admin/modifiers/page.tsx",
        "app/admin/modifiers/[id]/ModifierEditForm.tsx",
        "app/admin/modifiers/[id]/page.tsx",
        "app/admin/modifiers/ModifierGroupManager.tsx",
        "app/signup/page.tsx",
        "app/sales/new/page.tsx",
        "app/sales/page.tsx",
        "app/sales/[id]/edit/page.tsx",
        "app/sales/[id]/page.tsx",
        "app/calendar/page.tsx",
        "app/predictions/new/page.tsx",
        "app/predictions/page.tsx",
        "app/predictions/performance/page.tsx",
        "app/predictions/[id]/page.tsx",
        "app/layout.tsx",
        "app/settings/page.tsx",
        "app/login/page.tsx",
        "app/order/ProductList.tsx",
        "app/order/cart/page.tsx",
        "app/order/page.tsx",
        "app/order/success/[orderNumber]/page.tsx",
        "app/order/checkout/page.tsx",
        "app/order/checkout/CheckoutForm.tsx",
        "app/actions/auth.ts",
        "app/actions/order.ts",
        "app/actions/subscription.ts",
        "app/imports/new/page.tsx",
        "app/imports/page.tsx",
        "app/imports/[id]/page.tsx",
        "app/subscribe/SubscribeForm.tsx",
        "app/subscribe/page.tsx",
        "app/tasks/page.tsx",
        "app/tasks/[id]/page.tsx",
        "app/page.tsx",
        "app/analytics/layout.tsx",
        "app/analytics/weekly/page.tsx",
        "app/analytics/segments/page.tsx",
        "app/analytics/daily/page.tsx",
        "app/analytics/page.tsx",
        "app/analytics/monthly/page.tsx",
        "app/weights/page.tsx",
        "app/account/profile/page.tsx",
        "app/account/profile/ProfileForm.tsx",
        "app/account/orders/[orderNumber]/CancelOrderButton.tsx",
        "app/account/orders/[orderNumber]/page.tsx",
        "app/account/orders/page.tsx",
        "app/account/page.tsx",
        "app/account/security/page.tsx",
        "app/account/security/PasswordForm.tsx",
        "app/account/subscriptions/page.tsx",
        "app/account/subscriptions/[id]/page.tsx",
        "app/account/subscriptions/[id]/SubscriptionActions.tsx",
        "app/external-factors/page.tsx",
        "app/external-factors/[date]/page.tsx",
        "app/staff/page.tsx",
        "app/dashboard/page.tsx",
        "app/api/admin/products/route.ts",
        "app/api/admin/products/[id]/route.ts",
        "app/api/admin/products/[id]/option-groups/[groupId]/route.ts",
        "app/api/admin/products/[id]/option-groups/[groupId]/options/route.ts",
        "app/api/admin/products/[id]/option-groups/[groupId]/options/[optionId]/route.ts",
        "app/api/admin/products/[id]/option-groups/route.ts",
        "app/api/admin/products/[id]/modifier-group-assignments/[groupId]/route.ts",
        "app/api/admin/products/[id]/modifier-group-assignments/route.ts",
        "app/api/admin/modifier-groups/route.ts",
        "app/api/admin/modifier-groups/[id]/route.ts",
        "app/api/admin/modifier-groups/[id]/options/route.ts",
        "app/api/admin/modifier-groups/[id]/options/[optionId]/route.ts",
        "app/api/admin/categories/route.ts",
        "app/api/admin/integrations/loyverse/sync/route.ts",
        "app/api/admin/integrations/loyverse/full-sync/route.ts",
        "app/api/admin/sync/orders/retry/route.ts",
        "app/api/admin/users/route.ts",
        "app/api/admin/users/[id]/route.ts",
        "app/api/admin/subscriptions/route.ts",
        "app/api/admin/subscriptions/[id]/route.ts",
        "app/api/admin/inventory/route.ts",
        "app/api/admin/subscription-occurrences/route.ts",
        "app/api/admin/subscription-occurrences/[id]/route.ts",
        "app/api/admin/modifiers/route.ts",
        "app/api/admin/modifiers/[id]/route.ts",
        "app/api/sales/route.ts",
        "app/api/sales/[id]/route.ts",
        "app/api/sales/[id]/collect-external/route.ts",
        "app/api/predictions/route.ts",
        "app/api/predictions/performance/route.ts",
        "app/api/predictions/[id]/route.ts",
        "app/api/internal/jobs/daily-order-push/route.ts",
        "app/api/settings/route.ts",
        "app/api/imports/route.ts",
        "app/api/imports/[id]/route.ts",
        "app/api/imports/[id]/execute/route.ts",
        "app/api/imports/[id]/collect-external/route.ts",
        "app/api/analytics/route.ts",
        "app/api/analytics/weekly/route.ts",
        "app/api/analytics/segments/route.ts",
        "app/api/analytics/daily/route.ts",
        "app/api/analytics/monthly/route.ts",
        "app/api/weights/route.ts",
        "app/api/weights/[id]/route.ts",
        "app/api/account/profile/route.ts",
        "app/api/account/subscriptions/route.ts",
        "app/api/account/subscriptions/[id]/route.ts",
        "app/api/account/password/route.ts",
        "app/api/external-factors/route.ts",
        "app/api/external-factors/[date]/route.ts",
        "prisma/seed.ts",
        "lib/__tests__/weather.test.ts",
        "lib/__tests__/subscriptionService.test.ts",
        "lib/task-utils.ts",
        "lib/integrations/services/loyverse-mirror-sync.ts",
        "lib/prediction-utils.ts",
        "lib/validations.ts",
        "lib/analytics-utils.ts",
        "lib/utils/weather-icon.ts",
        "lib/auth/dal.ts",
        "lib/services/taskService.ts",
        "lib/services/externalFactorService.ts",
        "lib/services/importService.ts",
        "lib/services/predictionService.ts",
        "lib/services/analytics/index.ts",
        "lib/services/subscriptionService.ts",
        "lib/services/daily-order-push.ts",
        "lib/services/schedulerService.ts",
        "lib/csv-parser.ts",
        "lib/providers/weather/index.ts",
        "lib/providers/holiday/index.ts",
    ]

    changed = 0
    skipped = 0
    errors = 0

    for rel_path in target_files:
        filepath = os.path.join(project_root, rel_path)
        if not os.path.exists(filepath):
            print(f"  SKIP (not found): {rel_path}")
            skipped += 1
            continue
        was_changed, _ = process_file(filepath)
        if was_changed:
            print(f"  CHANGED: {rel_path}")
            changed += 1

    print(f"\nDone: {changed} files changed, {skipped} skipped, {errors} errors")

    # Also process any remaining files with Korean
    print("\nScanning for remaining Korean in all ts/tsx files...")
    import subprocess
    result = subprocess.run(
        ["find", project_root, "-type", "f", "(", "-name", "*.ts", "-o", "-name", "*.tsx", ")"],
        capture_output=True, text=True
    )
    all_files = result.stdout.strip().split('\n') if result.stdout.strip() else []

    extra_changed = 0
    for filepath in all_files:
        if not filepath:
            continue
        rel = filepath.replace(project_root + '/', '')
        # Check if Korean exists
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            if re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', content):
                was_changed, _ = process_file(filepath)
                if was_changed:
                    print(f"  EXTRA CHANGED: {rel}")
                    extra_changed += 1
        except (UnicodeDecodeError, IOError):
            pass

    print(f"Extra files changed: {extra_changed}")


if __name__ == "__main__":
    main()
