#!/usr/bin/env python3
"""Second pass: fix garbled text and translate remaining Korean."""

import os
import re
import subprocess

PROJECT_ROOT = "/home/runner/work/Beyond/Beyond"

# Fix garbled text FIRST (single-syllable bad replacements created these)
GARBLED_FIXES = [
    # "행" replaced "행" in "실행" (execute/run)
    ("실Rows에 실패했습니다", "failed to execute"),
    ("실Rows 중…", "Running..."),
    ("실Rows 중...", "Running..."),
    ("실Rows하세요", "Run now"),
    ("실Rows하면", "when run"),
    ("실Rows된 적 없습니다", "has never been run"),
    ("실Rows됩니다", "will be run"),
    ("재실Rows하세요", "Re-run"),
    ("✓ 실Rows 완료", "✓ Run complete"),
    ("임포트 실Rows에 실패했습니다", "Import execution failed"),
    ("Rows 임포트 실Rows", "Rows import run"),
    ("🔮 Predictions 실Rows 중...", "🔮 Running Predictions..."),
    ("🔮 Predictions 실Rows", "🔮 Run Predictions"),
    ("작업 실Rows Status를 관리합니다", "Manage scheduled task run status"),
    ("위 버튼을 눌러 작업을 실Rows해보세요", "Click the button above to run a task"),
    ("실Rows", "Run"),
    # "건" replaced in "조건" (condition/filter)
    ("조items에 맞는", "No results matching your filters"),
    ("Filter 조items을 변경해보세요", "Try changing your filter conditions"),
    ("조items별 비교", "Compare by condition"),
    ("조items", "conditions"),
    # "건" replaced in "건너뜀" (skipped)
    ("items너뜀", "Skipped"),
    # "비활성화" / "비활성" garbling
    ("비Activate할 수 없습니다", "cannot be deactivated"),
    ("비Activate", "Deactivate"),
    ("비Active", "Inactive"),
    # Date labels garbled
    ("마지막Edit일", "Last Edit Date"),
    ("마지막Edit", "Last Edit"),
    ("Create일시", "Created At"),
    ("Create일", "Created Date"),
    ("Orders일", "Order Date"),
    ("Pickup일", "Pickup Date"),
    ("Pickup일시", "Pickup At"),
    # "일" replaced at end of words
    ("시작days", "Start Date"),
    ("종료days", "End Date"),
    ("가입days", "Join Date"),
    ("예약days", "Reserved days"),
    # Remaining garbled combo patterns
    ("Orders번호", "Order Number"),
    ("Products명", "Product Name"),
    ("Products ID", "Product ID"),
    ("그룹 Name", "Group Name"),
    ("Products-Modifiers링크", "Product-Modifier links"),
    ("Modifiers그룹", "Modifier groups"),
    ("Modifiers옵션", "Modifier options"),
    ("신규Products", "New products"),
    ("업데이트Products", "Updated products"),
    ("Categories에 Link되지 않은 Products입니다. Sync 후 자동으로 Link됩니다.", "Products not linked to Categories. They will be linked automatically after Sync."),
    ("Modifiers 그룹 ID를 입력해주세요", "Please enter a Modifier Group ID"),
    ("Products ID를 입력해주세요", "Please enter a Product ID"),
    ("Products명을 입력해주세요", "Please enter a product name"),
    ("상점 Name을 입력해주세요", "Please enter a store name"),
    ("상점 Name", "Store Name"),
    ("변경 Unavailable", "Cannot be changed"),
    ("내 Subscriptions", "My Subscriptions"),
    ("Subscriptions List을 Confirm하세요", "View your subscription list"),
    ("Subscriptions이 없습니다", "No subscriptions yet"),
    ("Subscriptions을 Cancel하시겠습니까?", "Cancel this subscription?"),
    ("Subscriptions Cancel", "Cancel Subscription"),
    ("Pickup 정보", "Pickup Info"),
    ("결제 수단", "Payment Method"),
    ("내 Subscriptions", "My Subscriptions"),
    ("Password 변경", "Change Password"),
    ("Inventory Management 페이지 →", "Inventory Management page →"),
    ("Modifier 관리", "Modifier Management"),
    # "총 Sold 베이글" partial translation
    ("총 Sold 베이글", "Total Sold Bagels"),
    ("Remaining 베이글", "Remaining Bagels"),
    ("Sold 베이글", "Sold Bagels"),
    ("베이글 Error", "Bagel Error"),
    ("Sold 베이글 수량", "Sold Bagels Qty"),
    ("예상 Sold율", "Estimated Sell-through Rate"),
    ("예상 Sold량", "Estimated Sold Qty"),
    ("평균 일 Sales", "Daily Avg. Sales"),
    ("평균 일 Sold 베이글", "Daily Avg. Sold Bagels"),
    ("일반일 평균 Sales", "Regular Day Avg. Sales"),
    ("Holiday 평균 Sales", "Holiday Avg. Sales"),
    ("School Holiday Period 평균 Sales", "School Holiday Period Avg. Sales"),
    ("학기 중 평균 Sales", "In-Term Avg. Sales"),
    ("Store Sales 비중", "Store Sales Share"),
    ("Uber이츠 비중", "Uber Eats Share"),
    ("DoorDash 비중", "DoorDash Share"),
    ("채널 비중", "Channel Share"),
    ("채널별", "By Channel"),
    ("채널", "Channel"),
    ("Other 비중", "Other Share"),
    ("Store 비중", "Store Share"),
    ("Uber 비중", "Uber Share"),
    ("전월 대비", "vs. Last Month"),
    ("전주 대비", "vs. Last Week"),
    ("All 대비", "vs. All"),
    ("이번 달 vs 지난 달", "This month vs. last month"),
    ("최근 7일 vs 이전 7일", "Last 7 days vs. previous 7 days"),
    ("기준 Sales", "Baseline Sales"),
    ("평균 Sales", "Avg. Sales"),
    ("평균 Sold", "Avg. Sold"),
    ("Sold 비중", "Sold Share"),
    ("해당 Period Daily Avg. Sales 대비 각 요일 평균 Sales의 증감률", 
     "Change rate of each day's avg. sales vs. the period daily avg. sales"),
    ("이번 달 기록", "This Month Records"),
    ("이번 달 매출", "This Month Sales"),
    ("일평균 매출", "Daily Avg. Sales"),
    ("지난 달 매출", "Last Month Sales"),
    ("추천 생산", "Recommended Production"),
    # Collections
    ("수집 중...", "Collecting..."),
    ("수집 버튼을 눌러 수집하세요", "click the collect button"),
    ("수집 버튼을 다시 눌러 재시도하세요", "click the collect button again to retry"),
    ("수집에 실패했습니다", "Collection failed"),
    ("수집 실패 —", "Collection failed —"),
    ("수집 실패", "Collection failed"),
    ("🔄 External Data 수집", "🔄 Collect External Data"),
    ("🌐 External Data 재수집", "🌐 Re-collect External Data"),
    ("External Data 자동 수집", "Automatic External Data Collection"),
    ("수집: ", "Collected: "),
    ("수집 완료", "Collection complete"),
    ("수집 중", "Collecting"),
    ("수집", "Collect"),
    ("Weather Data가 없습니다.", "No weather data available."),
    ("Weather 수집 실패 —", "Weather collection failed —"),
    # UI action terms
    ("로그아웃 중…", "Signing out..."),
    ("로그아웃", "Sign out"),
    ("사이드바 네비게이션", "sidebar navigation"),
    ("상단 바", "top bar"),
    ("모바일 네비게이션", "mobile navigation"),
    ("Menu 열기", "Open Menu"),
    # Role labels
    ("직원", "Staff"),
    ("고객", "Customer"),
    ("스태프", "Staff"),
    # Status labels
    ("임시", "Draft"),
    ("접수됨", "Received"),
    ("Confirm됨", "Confirmed"),
    ("준비중", "Preparing"),
    ("준비완료", "Ready"),
    ("Cancel됨", "Cancelled"),
    ("예약됨", "Scheduled"),
    # Security/profile
    ("프로필이 업데이트되었습니다", "Profile updated"),
    ("프로필 업데이트에 실패했습니다", "Failed to update profile"),
    ("Password가 변경되었습니다", "Password changed"),
    ("변경에 실패했습니다", "Change failed"),
    ("New Password가 일치하지 않습니다", "New passwords do not match"),
    ("요청 중 오류가 발생했습니다", "An error occurred while processing"),
    ("Name을 입력하세요", "Please enter your name"),
    # More validation messages
    ("Password는 8자 이상이어야 합니다", "Password must be at least 8 characters"),
    ("Password에 숫자가 포함되어야 합니다", "Password must contain a number"),
    ("Password에 영문자가 포함되어야 합니다", "Password must contain a letter"),
    ("이미 사용 중인 Email입니다", "Email is already in use"),
    ("Password가 일치하지 않습니다", "Passwords do not match"),
    ("올바른 Email을 입력해주세요", "Please enter a valid email"),
    ("Password를 입력해주세요", "Please enter your password"),
    ("Current Password를 입력해주세요", "Please enter your current password"),
    ("Confirm Password을 입력해주세요", "Please enter password confirmation"),
    ("Name을 입력해주세요", "Please enter your name"),
    ("Name이 너무 깁니다", "Name is too long"),
    ("0 이상의 정수를 입력해주세요", "Please enter an integer of 0 or more"),
    ("0~1 사이의 값을 입력해주세요", "Please enter a value between 0 and 1"),
    ("0 이상의 값을 입력해주세요", "Please enter a value of 0 or more"),
    ("가격은 0 이상이어야 합니다", "Price must be 0 or more"),
    ("1 이상의 값을 입력해주세요", "Please enter a value of 1 or more"),
    ("수량은 0 이상이어야 합니다", "Quantity must be 0 or more"),
    ("Date 형식이 올바르지 않습니다", "Invalid date format"),
    ("Date를 Please select", "Please select a date"),
    ("Date를 입력해주세요", "Please enter a date"),
    ("그룹명을 입력해주세요", "Please enter a group name"),
    ("옵션 그룹명을 입력해주세요", "Please enter an option group name"),
    ("옵션명을 입력해주세요", "Please enter an option name"),
    ("장바구니가 비어 있습니다", "Cart is empty"),
    ("키를 입력해주세요", "Please enter a key"),
    ("Pickup 시간을 Please select", "Please select a pickup time"),
    ("입력 오류", "Input error"),
    ("입력값이 올바르지 않습니다", "Invalid input"),
    ("올바르지 않은 Pickup Date입니다. 영업일(월~토)을 Please select", "Invalid pickup date. Please select a business day (Mon–Sat)"),
    ("올바르지 않은 Pickup 시간입니다", "Invalid pickup time"),
    ("올바르지 않은 Pickup", "Invalid pickup"),
    ("올바르지 않은", "Invalid"),
    ("선택 입력", "Optional input"),
    # Korean order messages
    ("이미 완료되거나 Cancel된 Orders입니다", "Order is already completed or cancelled"),
    ("이전 Status로 되돌릴 수 없습니다", "Cannot revert to previous status"),
    ("Cancel할 수 없는 Orders Status입니다", "Order cannot be cancelled in this status"),
    ("Orders Create 중 오류가 발생했습니다", "Error creating order"),
    ("Orders을 Not found", "Order not found"),
    ("Orders할 수 없는 Products이 포함되어 있습니다", "Contains products that cannot be ordered"),
    ("Status 변경 중 오류가 발생했습니다", "Error changing status"),
    ("장바구니 Data가 올바르지 않습니다", "Invalid cart data"),
    ("Cancel Processing... 오류가 발생했습니다", "Error processing cancellation"),
    ("Cancel 후에는 되돌릴 수 없습니다", "This action cannot be undone after cancellation"),
    ("정말 Orders을 Cancel하시겠습니까?", "Are you sure you want to cancel this order?"),
    ("Cancel Processing...", "Processing cancellation..."),
    ("Pickup 2시간 이내에는 Cancel할 수 없습니다", "Cannot cancel within 2 hours of pickup"),
    ("수량이 올바르지 않습니다", "Invalid quantity"),
    ("옵션 그룹을 Not found", "Option group not found"),
    ("옵션을 Not found", "Option not found"),
    ("Products을 Not found", "Product not found"),
    # Options/choices
    ('"의 "${group.name}" 옵션을 Please select`', 'please select "${group.name}" option`'),
    # Payment
    ("현장 결제 예정", "On-site payment"),
    ("결제 Status", "Payment Status"),
    ("합계", "Total"),
    # Account page strings
    ("아직 Orders 내역이 없습니다", "No order history yet"),
    ("Users 정보를 불러올 수 없습니다", "Unable to load user information"),
    ("계정 정보 및 Settings을 관리하세요", "Manage your account information and settings"),
    ("Pickup 정보", "Pickup Info"),
    ("내 Subscriptions", "My Subscriptions"),
    ("가입일", "Join Date"),
    ("권한", "Role"),
    ("곧 Link될 예정", "Coming soon"),
    ("Save된 Pickup 메모 및 연락 정보를 관리합니다", "Manage your saved pickup notes and contact info"),
    ("Orders 내역 및 Status를 Confirm할 수 있습니다", "View your order history and status"),
    ("정기 Subscriptions 및 플랜을 관리할 수 있습니다", "Manage your recurring subscriptions and plans"),
    ("정기 Subscriptions List을 Confirm하세요", "View your recurring subscription list"),
    ("등록된 결제 수단을 Confirm하고 관리합니다", "View and manage your registered payment methods"),
    ("Orders List 보기 →", "View Orders →"),
    ("Subscriptions List 보기 →", "View Subscriptions →"),
    ("기본 프로필 정보를 Edit하세요", "Edit your basic profile information"),
    ("아직 Subscriptions이 없습니다", "No subscriptions yet"),
    ("종료일", "End Date"),
    ("시작일", "Start Date"),
    ("발생 내역", "Occurrence History"),
    ("메모", "Notes"),
    # Subscription actions  
    ("재개하기", "Resume"),
    ("처리중...", "Processing..."),
    # Predictions page
    ("지금 Predictions을 Create하면 생산량 추천을 받을 수 있습니다", 
     "Create a prediction now to get a production recommendation"),
    ("내일({tomorrowStr}) Predictions이 아직 없습니다", 
     "No prediction yet for tomorrow ({tomorrowStr})"),
    ("Predictions 결과와 실제 실적 비교 (최근 30items)", 
     "Compare prediction results with actual performance (last 30 items)"),
    ("총 Predictions items수", "Total Predictions"),
    ("최근 30items 기준", "Based on last 30 items"),
    ("{comparableCount}items 비교 Available", "{comparableCount} items available for comparison"),
    ("정확 <span", "accurate <span"),
    ("items 정확 <span", " accurate <span"),
    # Imports page
    ("Internal Sales Data CSV 임포트 ({jobs.length}items)", 
     "Internal Sales Data CSV Import ({jobs.length} items)"),
    ("일별 Sales Records ({records.length}items)", 
     "Daily Sales Records ({records.length} items)"),
    ("Sales Predictions 결과 ({predictions.length}items)", 
     "Sales Predictions results ({predictions.length} items)"),
    ("스케줄된 작업과 실Rows Status를 관리합니다", 
     "Manage scheduled tasks and their run status"),
    # Weather labels
    ("강수량 (mm)", "Rainfall (mm)"),
    ("강수량", "Rainfall"),
    ("바람", "Wind"),
    ("최고 기온 (°C)", "Max Temp (°C)"),
    ("최저 기온 (°C)", "Min Temp (°C)"),
    ("최고 기온", "Max Temp"),
    ("최저 기온", "Min Temp"),
    ("로컬 Event", "Local Event"),
    ("지역 Event", "Local Event"),
    ("Weather 요약", "Weather Summary"),
    ("NZ News 요약", "NZ News Summary"),
    ("World News 요약", "World News Summary"),
    ("풍속 (kph)", "Wind Speed (kph)"),
    ("풍속", "Wind Speed"),
    ("가게 정보", "Store Info"),
    # Table headers
    ("요일", "Day"),
    ("출처", "Source"),
    ("비중", "Share"),
    ("효과", "Effect"),
    ("금액", "Amount"),
    ("로그", "Log"),
    ("기록 수", "Record Count"),
    ("작업 유형", "Task Type"),
    ("작업", "Task"),
    ("시작", "Started"),
    ("완료", "Completed"),
    ("파일명", "File Name"),
    ("수집 시각", "Collected At"),
    ("재시도", "Retry"),
    ("성공", "Success"),
    ("실패", "Failed"),
    ("총 Rows", "Total Rows"),
    ("요인 키", "Factor Key"),
    ("설명", "Description"),
    ("액션", "Actions"),
    ("옵션", "Options"),
    ("값", "Value"),
    ("요인", "Factor"),
    ("영향 (Sales)", "Impact (Sales)"),
    ("마지막 Sync", "Last Sync"),
    ("가격", "Price"),
    ("정렬순서", "Sort Order"),
    ("Edit일", "Last Edit"),
    ("일수", "Days"),
    # More missing terms
    ("외부요인", "External Factors"),
    ("기준값", "baseline value"),
    ("기준", "baseline"),
    ("최근", "recent"),
    ("평균", "average"),
    ("Waste Rate을 고려해 Sold량 대비 10% 버퍼 적용", 
     "Applying 10% buffer over predicted sold qty based on Waste Rate"),
    ("Waste Rate을 고려해 예상 Sold량 대비", 
     "Based on recent Waste Rate, applying buffer over estimated Sold Qty"),
    ("버퍼를 적용한 생산량 추천", "buffer applied production recommendation"),
    ("요일 Weights 반영", "day-of-week weights applied"),
    ("요일 Weights가 반영됨", "day-of-week weights were applied"),
    ("이 기준값으로 사용됨", "is used as the baseline"),
    ("이 기준값(", "as the baseline ("),
    ("원)이 기준값으로 사용됨", ") is used as the baseline"),
    ("원)으로 사용됨", ") is used as the baseline"),
    ("평균 Sales이 기준값으로 사용됨", "avg. sales is used as the baseline"),
    ("평균 Sales이", "avg. sales"),
    ("평균 Sales(", "avg. sales ("),
    ("원) 이", ") "),
    ("원", ""),   # currency unit - context is already shown by formatCurrency
    ("Weights는 Predicted Sales 대비 비율입니다", 
     "Weights are ratios relative to Predicted Sales"),
    ("Predictions이 있지만 비교할 실제 Data가 아직 없습니다. Predictions Date의 Actual Sales을 입력하면 Performance를 비교할 수 있습니다",
     "Predictions exist but no actual data to compare yet. Enter Actual Sales for the prediction date to compare performance"),
    # Sync messages
    ("Loyverse All Sync 중 오류가 발생했습니다", "Error during Loyverse Full Sync"),
    ("Sync 중 오류가 발생했습니다", "Error during Sync"),
    ("modifier Sync가 실Rows된 적 없습니다", "modifier sync has never been run"),
    ("아직 Loyverse All Sync가 실Rows된 적 없습니다. 아래 버튼으로 Sync하세요", 
     "Loyverse Full Sync has never been run. Use the button below to sync"),
    ("아직 Sync된 Categories가 없습니다. Loyverse Sync를 실Rows하세요", 
     "No synced Categories yet. Run Loyverse Sync"),
    ("Loyverse 카탈로그 Sync를 실Rows하면 Modifier 그룹이 자동으로 Create됩니다",
     "Running Loyverse catalog Sync will automatically create Modifier groups"),
    ("✓ 마지막 All Sync 성공", "✓ Last Full Sync successful"),
    ("⚠ 마지막 All Sync 부분 완료", "⚠ Last Full Sync partially complete"),
    ("✓ Loyverse 마지막 All Sync 성공", "✓ Loyverse Last Full Sync successful"),
    ("⚠ Loyverse 마지막 All Sync 부분 완료", "⚠ Loyverse Last Full Sync partially complete"),
    ("▲ 수동 입력 숨기기", "▲ Hide manual input"),
    # Loyverse sync button labels
    ("🔄 Loyverse All Sync", "🔄 Loyverse Full Sync"),
    ("🔄 Loyverse 카탈로그 Sync", "🔄 Loyverse Catalog Sync"),
    # Modifier page
    ("아직 modifier Sync가 실Rows된 적 없습니다", "Modifier sync has never been run"),
    ("Remove된 stale 링크: {result.staleLinksRemoved}items", 
     "Stale links removed: {result.staleLinksRemoved}"),
    ("오류: {result.errorCount}items", "Errors: {result.errorCount}"),
    ("⚠ 오류: {result.errorCount}items", "⚠ Errors: {result.errorCount}"),
    # Admin sync page
    ("아래에서 수동 전송하거나 상단 버튼으로 All 재실Rows하세요", 
     "Manually send below or re-run all with the top button"),
    ("❌ 전송 실패 Orders ({failedOrders.length}items)", 
     "❌ Failed to Send Orders ({failedOrders.length})"),
    ("✅ 전송 성공 Orders ({successOrders.length}items)", 
     "✅ Successfully Sent Orders ({successOrders.length})"),
    ("지금 자동 전송 실Rows", "Run Auto-Send Now"),
    ("Today({todayStr}) Pickup 예정 Orders의 Loyverse 자동 전송 Status",
     "Loyverse auto-send status for today's ({todayStr}) scheduled pickup orders"),
    # Admin page
    ("Enter Sales하기 →", "Enter Sales →"),
    # Success results
    ("✓ Done — 성공 {result.pushSucceeded ?? 0}items / 실패 {result.pushFailed ?? 0}items / 이미 전송됨",
     "✓ Done — Success {result.pushSucceeded ?? 0} / Failed {result.pushFailed ?? 0} / Already sent"),
    # ImportId page
    ("외부요인", "External Factors"),
    ("임포트 중...", "Importing..."),
    ("임포트 실Rows", "Run Import"),
    ("파싱된 Rows이 없습니다", "No parsed rows"),
    ("이 내용이 업로드 파일보다 우선 적용됩니다", "This content takes priority over the uploaded file"),
    ("CSV 파일을 드래그하거나 클릭하여 선택", "Drag or click to select a CSV file"),
    ("📤 업로드 및 검증", "📤 Upload and Validate"),
    ("📋 템플릿 복사", "📋 Copy Template"),
    # Counts with 개 suffix in JSX  
    ("{activeCount}개 Active", "{activeCount} Active"),
    ("{cat.products.length}개 Products", "{cat.products.length} Products"),
    ("{uncategorisedCount}개 Products", "{uncategorisedCount} Products"),
    ("{modifierCount}개", "{modifierCount}"),
    ("{factors.length}개", "{factors.length}"),
    ("{result.errors.length}개", "{result.errors.length}"),
    # Bagels count
    ("{getSoldBagels(record)}개", "{getSoldBagels(record)}"),
    ("{month.totalBagelsSold}개", "{month.totalBagelsSold}"),
    ("{record.bagelsLeft}개", "{record.bagelsLeft}"),
    ("{week.totalBagelsSold}개", "{week.totalBagelsSold}"),
    ("{Math.round(h.avgBagelsSold)}개", "{Math.round(h.avgBagelsSold)}"),
    ("{item.bagelsSold}개", "{item.bagelsSold}"),
    ("{prediction.predictedBagelsSold}개", "{prediction.predictedBagelsSold}"),
    ("{prediction.recommendedBagelsToBake}개", "{prediction.recommendedBagelsToBake}"),
    ("{p.predictedBagelsSold}개", "{p.predictedBagelsSold}"),
    ("{p.recommendedBagelsToBake}개", "{p.recommendedBagelsToBake}"),
    ("{comparison.actualBagelsSold}개", "{comparison.actualBagelsSold}"),
    ("`${comparison.actualBagelsSold}개`", "`${comparison.actualBagelsSold}`"),
    ("`${comparison.actualLeftovers}개`", "`${comparison.actualLeftovers}`"),
    ("`${comparison.predictedBagelsSold}개`", "`${comparison.predictedBagelsSold}`"),
    ("`${comparison.predictedLeftovers}개`", "`${comparison.predictedLeftovers}`"),
    ("{row.recordCount}일", "{row.recordCount} days"),
    ("{monthComparison.current.recordCount}일", "{monthComparison.current.recordCount} days"),
    ("`${Math.round(row.avgBagelsSold)}개`", "`${Math.round(row.avgBagelsSold)}`"),
    ("{Math.round(row.avgBagelsSold)}개", "{Math.round(row.avgBagelsSold)}"),
    ("1개", "1"),
    # Units
    ("굽", " baked"),
    # Various patterns
    ("결과 ({predictions.length}items)", "results ({predictions.length})"),
    ("오류 Details (최대 5items)", "Error Details (max 5)"),
    ("최대 5items", "max 5"),
    ("선택 {group.minSelect}~{group.maxSelect}개", "Select {group.minSelect}~{group.maxSelect}"),
    ("선택 {group.minSelect}~{group.maxSelect}개 · {group.options.length} options",
     "Select {group.minSelect}~{group.maxSelect} · {group.options.length} options"),
    ("🔗 Loyverse {loyverseCount}개", "🔗 Loyverse {loyverseCount}"),
    ("{importResult.skippedRows}items", "{importResult.skippedRows}"),
    ("대상 Date {importResult.externalCollect.totalDates ?? 0}items", 
     "Target dates: {importResult.externalCollect.totalDates ?? 0}"),
    ("처리 {importResult.externalCollect.processedDates ?? 0}items",
     "Processed: {importResult.externalCollect.processedDates ?? 0}"),
    ("총 {latestImportJob.totalRows}Rows · 성공 {latestImportJob.successRows} · 실패 {latestImportJob.failedRows}",
     "Total {latestImportJob.totalRows} rows · Success {latestImportJob.successRows} · Failed {latestImportJob.failedRows}"),
    ("총 {job.totalRows}Rows · 유효 {validRows}Rows",
     "Total {job.totalRows} rows · Valid {validRows} rows"),
    ("성공: {importResult.successRows}items · Failed: {importResult.failedRows}items · items너뜀: {importResult.skippedRows}items",
     "Success: {importResult.successRows} · Failed: {importResult.failedRows} · Skipped: {importResult.skippedRows}"),
    ("오류: {result.errors.length}개", "Errors: {result.errors.length}"),
    ("✗ Unmapped (Active) {unmappedActiveCount}개", "✗ Unmapped (Active) {unmappedActiveCount}"),
    ("🔗 Loyverse {n}개", "🔗 Loyverse {n}"),
    # Prediction service strings  
    ("기준으로", "as the basis for"),
    ("개 생산을 추천합니다", "production recommended"),
    ("개 × 1.1 =", "× 1.1 ="),
    ("개 이상이어야 합니다", " or more required"),
    # saveLabel prop
    ('saveLabel="옵션 Add"', 'saveLabel="Add Option"'),
    # Dynamic template strings in services
    ("`${predictedBagelsSold} 기준으로 ${recommendedBagelsToBake}개 생산을 추천합니다.`",
     "`Recommend ${recommendedBagelsToBake} production based on ${predictedBagelsSold} predicted sales.`"),
    ("`${predictedBagelsSold} 기준으로 `", "`Based on ${predictedBagelsSold}: `"),
    # Month header
    ("{year}년 {month}월", "{year}/{month}"),
    ("{year}년 {month}월 {day}일", "{year}/{month}/{day}"),
    ("`${year}년 ${month}월 ${day}일", "`${year}/${month}/${day}"),
    (" 실적 Yes", " has actual data"),
    # Prediction detail string
    (" Predictions이 있지만", " Predictions exist but"),
    # Day of week
    ("일요일", "Sunday"),
    ("월요일", "Monday"),
    ("화요일", "Tuesday"),
    ("수요일", "Wednesday"),
    ("목요일", "Thursday"),
    ("금요일", "Friday"),
    ("토요일", "Saturday"),
    # Short day names in WEEKDAYS arrays
    ('"일", "월", "화", "수", "목", "금", "토"', '"Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"'),
    ("['일', '월', '화', '수', '목', '금', '토']", "['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']"),
    ('["일","월요일","화요일","수요일","목요일","금요일","토요일"]', '["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]'),
    ('["일요일","월요일","화요일","수요일","목요일","금요일","토요일"]', '["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]'),
    # User table
    ("All <strong", "All <strong"),
    ('(All {summary.total}명)', '(All {summary.total})'),
    ("Search 결과 <strong", "Search results <strong"),
    ("<strong className=\"text-gray-700\">{users.length}</strong>명", 
     "<strong className=\"text-gray-700\">{users.length}</strong>"),
    # Filter text
    ("Filter 조items을 변경해보세요.", "Try changing your filter conditions."),
    ("새 Products을 Add해보세요.", "Try adding new Products."),
    # Loyverse sync result counts  
    ("<span>Categories {lastFullSync.categoriesUpserted}개</span>",
     "<span>Categories {lastFullSync.categoriesUpserted}</span>"),
    ("<span>Modifiers그룹 {lastFullSync.modifierGroupsUpserted}개</span>",
     "<span>Modifier groups {lastFullSync.modifierGroupsUpserted}</span>"),
    ("<span>Modifiers옵션 {lastFullSync.modifierOptionsUpserted}개</span>",
     "<span>Modifier options {lastFullSync.modifierOptionsUpserted}</span>"),
    ("<span>Products-Modifiers링크 {lastFullSync.modifierLinksUpdated}개</span>",
     "<span>Product-modifier links {lastFullSync.modifierLinksUpdated}</span>"),
    ("<span>신규Products {lastFullSync.productsCreated}개</span>",
     "<span>New products {lastFullSync.productsCreated}</span>"),
    ("<span>업데이트Products {lastFullSync.productsUpdated}개</span>",
     "<span>Updated products {lastFullSync.productsUpdated}</span>"),
    # Modifier groups table
    ("<> · 그룹 {lastFullSync.modifierGroupsUpserted}개 · 옵션 {lastFullSync.modifierOptionsUpserted}개 · 링크 {lastFullSync.modifierLinksUpdated}items</>",
     "<> · Groups {lastFullSync.modifierGroupsUpserted} · Options {lastFullSync.modifierOptionsUpserted} · Links {lastFullSync.modifierLinksUpdated}</>"),
    # Various remaining
    ("아직 Orders 내역이 없습니다", "No order history yet"),
    ("DRAFT: \"임시\"", 'DRAFT: "Draft"'),
    ("PENDING: \"접수됨\"", 'PENDING: "Received"'),
    ("CONFIRMED: \"Confirm됨\"", 'CONFIRMED: "Confirmed"'),
    ("PREPARING: \"준비중\"", 'PREPARING: "Preparing"'),
    ("READY: \"준비완료\"", 'READY: "Ready"'),
    ("COMPLETED: \"완료\"", 'COMPLETED: "Completed"'),
    ("CANCELLED: \"Cancel됨\"", 'CANCELLED: "Cancelled"'),
    ("SKIPPED: \"items너뜀\"", 'SKIPPED: "Skipped"'),
    ("SCHEDULED: \"예약됨\"", 'SCHEDULED: "Scheduled"'),
    # Options in product form
    ("옵션 {n}개", "{n} options"),
    ("그룹 {n}개", "{n} groups"),
    # Misc strings
    ("오류가 발생했습니다", "An error occurred"),
    ("Edit에 실패했습니다", "Edit failed"),
    ("Save에 실패했습니다", "Save failed"),
    ("Delete에 실패했습니다", "Delete failed"),
    ("재시도에 실패했습니다", "Retry failed"),
    ("처리에 실패했습니다", "Processing failed"),
    ("되돌릴 수 없습니다", "This action cannot be undone"),
    ("Delete하시겠습니까? 이 작업은 되돌릴 수 없습니다", 
     "Are you sure you want to delete? This action cannot be undone"),
    ("재시도 중…", "Retrying..."),
    ("✓ 재시도 완료", "✓ Retry complete"),
    ("🔄 재시도", "🔄 Retry"),
    ("오류가 발생했습니다", "An error occurred"),
    ("Inventory 수준", "Inventory Level"),
    ("Modifiers 옵션", "Modifier Options"),
    ("Loyverse Modifier 매핑 Status", "Loyverse Modifier Mapping Status"),
    ("Loyverse 카탈로그 Sync", "Loyverse Catalog Sync"),
    # Prediction page
    ("{new Date(p.createdAt).toLocaleString(\"ko-KR\")} 보기 →",
     "{new Date(p.createdAt).toLocaleString(\"en-NZ\")} View →"),
    ("{formatDate(new Date(dailyRecord.date))} 보기 →",
     "{formatDate(new Date(dailyRecord.date))} View →"),
    ("보기 →", "View →"),
    # locale
    ("\"ko-KR\"", "\"en-NZ\""),
    ("ko-KR", "en-NZ"),
    # WeightsManager
    ("요일", "Day"),
    ("뉴스", "News"),
    ("요인 키 *", "Factor Key *"),
    ("요인 설명 (선택)", "Factor description (optional)"),
    ('비Active"', 'Inactive"'),
    ("새 항목 Add", "Add New Entry"),
    ("💡 Weights 안내:", "💡 Weights Guide:"),
    ("Weights는 Predicted Sales 대비 비율입니다.", "Weights are ratios relative to Predicted Sales."),
    # FilterBar
    ("시작일", "Start Date"),
    ("종료일", "End Date"),
    ("키워드", "Keyword"),
    ("메모, Event, Holiday Search...", "Search notes, events, holidays..."),
    # Navigation
    ("STAFF: \"직원\"", 'STAFF: "Staff"'),
    ("CUSTOMER: \"고객\"", 'CUSTOMER: "Customer"'),
    ("STAFF: \"스태프\"", 'STAFF: "Staff"'),
    ("CUSTOMER: \"고객\"", 'CUSTOMER: "Customer"'),
    # Loyverse page
    ("기초 설정", "Basic Settings"),
    ("기타 정보", "Other Info"),
    ("// Loyverse Modifier 매핑 Menu Remove됨", "// Loyverse Modifier mapping menu removed"),
    ("// Loyverse Modifier 매핑 페이지 Remove됨", "// Loyverse Modifier mapping page removed"),
    # Import page
    ("외부요인", "External Factors"),
    ("파일명", "Filename"),
    ("대상 Date", "Target Date"),
    ("로그", "Log"),
    ("시작", "Started"),
    ("완료", "Completed"),
    ("작업 유형", "Task Type"),
    ("재시도", "Retry"),
    ("성공", "Success"),
    ("실패", "Failed"),
    # Additional remaining  
    ("placeholder=\"주요 NZ News...\"", "placeholder=\"Main NZ news...\""),
    ("placeholder=\"주요 World News...\"", "placeholder=\"Main world news...\""),
    ("placeholder=\"홍길동\"", "placeholder=\"John Smith\""),
    ("placeholder=\"맑음, 비, 흐림\"", "placeholder=\"clear, rain, cloudy\""),
    ("placeholder=\"맑음, 흐림, 비\"", "placeholder=\"clear, cloudy, rain\""),
    ("placeholder=\"베이글 선택\"", "placeholder=\"bagel selection\""),
    ("placeholder=\"지역 마켓\"", "placeholder=\"local market\""),
    ("placeholder=\"크리스마스\"", "placeholder=\"Christmas\""),
    ("placeholder=\"플레인 베이글\"", "placeholder=\"plain bagel\""),
    # seed.ts placeholders
    ("지역 마켓", "Local Market"),
    ("크리스마스", "Christmas"),
    ("플레인 베이글", "Plain Bagel"),
    ("베이글 선택", "Bagel Selection"),
    # Comments in weather-icon.ts
    ("* - 구름 / cloudy / overcast → ☁️", "* - cloud / cloudy / overcast → ☁️"),
    ("* - 뇌우 / thunderstorm → ⛈️", "* - thunderstorm → ⛈️"),
    ("* - 눈 / snow → ❄️", "* - snow → ❄️"),
    ("* - 맑음 / sunny / clear → ☀️", "* - sunny / clear → ☀️"),
    ("* - 바람 / windy → 💨", "* - windy → 💨"),
    ("* - 비 / rain / shower / drizzle → 🌧️", "* - rain / shower / drizzle → 🌧️"),
    ("* - 안개 / fog → 🌫️", "* - fog → 🌫️"),
    ("* - 정보 None → null (표시 안 함)", "* - no info → null (not displayed)"),
    # Navigation comment
    ("// Loyverse Modifier 매핑 메뉴 제거됨", "// Loyverse Modifier mapping menu removed"),
    # DB comment (고객 메뉴) - in navigation.ts type comment
    ("(고객 메뉴)", "(Customer Menu)"),
    # Error messages in services
    ("오류가 발생했습니다", "An error occurred"),
    ("실패했습니다", "failed"),
    # Analytics utils
    ("이번 달 vs 지난 달", "This month vs. last month"),
    # Day comparison
    ("같은 요일 평균이 All 평균보다", "Same-day average is"),
    ("원 반영됨 (", " applied ("),
    ("items 참고)", " data points reference)"),
    ("방향 반영됨", " applied"),
    # Remaining units  
    ("개", ""),  # bagel count suffix - remove when isolated
    # Prediction comparison strings
    ('`Event (${event.segment.recordCount}일)`', '`Event (${event.segment.recordCount} days)`'),
    ('`Holiday (${holiday.segment.recordCount}일)`', '`Holiday (${holiday.segment.recordCount} days)`'),
    ('`School Holiday (${schoolHoliday.segment.recordCount}일)`', '`School Holiday (${schoolHoliday.segment.recordCount} days)`'),
    ('`맑은 날 (${rain.baseline.recordCount}일)`', '`Clear days (${rain.baseline.recordCount} days)`'),
    ('`비 오는 날 (${rain.segment.recordCount}일)`', '`Rainy days (${rain.segment.recordCount} days)`'),
    ('`일반일 (${event.baseline.recordCount}일)`', '`Regular days (${event.baseline.recordCount} days)`'),
    ('`일반일 (${holiday.baseline.recordCount}일)`', '`Regular days (${holiday.baseline.recordCount} days)`'),
    ('`학기 중 (${schoolHoliday.baseline.recordCount}일)`', '`In-term (${schoolHoliday.baseline.recordCount} days)`'),
    ('`요일 (${dowLabel})`', '`Day (${dowLabel})`'),
    ('`${["일요일","월요일","화요일","수요일","목요일","금요일","토요일"][dow]} 요일 Weights 반영`',
     '`${["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][dow]} day-of-week weights applied`'),
    ('`${["일요일","월요일","화요일","수요일","목요일","금요일","토요일"][dow]} 요일 Weights가 반영됨`',
     '`${["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][dow]} day-of-week weights were applied`'),
    # analytics-utils  
    ('`최근 ${metrics.dataPointCount}일 평균 Sales(${Math.round(metrics.avgSales).toLocaleString("ko-KR")}원)이 기준값으로 사용됨`',
     '`Recent ${metrics.dataPointCount}-day avg. sales ($${Math.round(metrics.avgSales).toLocaleString("en-NZ")}) used as baseline`'),
    ('`최근 30일 평균 Sales이 기준값(${Math.round(baselineSales).toLocaleString("ko-KR")}원)으로 사용됨`',
     '`Recent 30-day avg. sales ($${Math.round(baselineSales).toLocaleString("en-NZ")}) used as baseline`'),
    ('`최근 Waste Rate(${(metrics.avgWasteRate * 100).toFixed(1)}%)을 고려해 예상 Sold량 대비 ${bufferPct}% 버퍼를 적용한 생산량 추천`',
     '`Production recommendation: ${bufferPct}% buffer over estimated sold qty based on recent Waste Rate (${(metrics.avgWasteRate * 100).toFixed(1)}%)`'),
    ('`최근 Waste Rate을 고려해 Sold량 대비 10% 버퍼 적용 (${predictedBagelsSold}개 × 1.1 = ${recommendedBagelsToBake}개)`',
     '`Applying 10% buffer over sold qty based on Waste Rate (${predictedBagelsSold} × 1.1 = ${recommendedBagelsToBake})`'),
    ('`같은 요일 평균이 All 평균보다 ${Math.abs(diff).toFixed(0)}원 ${direction} 반영됨 (${metrics.sameDayDataPointCount}items 참고)`',
     '`Same-day avg. is $${Math.abs(diff).toFixed(0)} ${direction} vs. overall avg. (${metrics.sameDayDataPointCount} data points)`'),
    ('`최근 ${metrics.dataPointCount}일`', '`Recent ${metrics.dataPointCount} days`'),
    # service strings
    ('최근 기록 None"', 'No recent records"'),
    ('`${input.totalDates}일`', '`${input.totalDates} days`'),
    ('`${input.processedDates}일`', '`${input.processedDates} days processed`'),
    ('`${input.skippedDates}일`', '`${input.skippedDates} days skipped`'),
    ('`${input.failedDates}일`', '`${input.failedDates} days failed`'),
    # 토요일 — 가장 Sales 높은 날 etc in prediction service
    ('"토요일 — 가장 Sales 높은 날"', '"Saturday — highest sales day"'),
    ('"화요일 — 평균 아래"', '"Tuesday — below average"'),
    ('"토요일"', '"Saturday"'),
    ('"화요일"', '"Tuesday"'),
    # Daily order push
    ("성공 {n}items / 실패 {m}items / 이미 전송됨", "Success {n} / Failed {m} / Already sent"),
    # subscription service
    ("이미 Cancel됨", "Already cancelled"),
    ("Cancel할 수 없는 Status", "Status cannot be cancelled"),
    ("Status가 올바르지 않습니다", "Invalid status"),
    # External factor  
    ("지역", "Local"),
    # Misc remaining Korean
    ("오류 {n}건", "Errors: {n}"),
    ("실패 {n}건", "Failed: {n}"),
    ("처리 {n}건", "Processed {n}"),
    ("대상 날짜 {n}건", "Target dates: {n}"),
    # CSV parser
    ("파싱", "parsing"),
    # Option in select
    ("선택 안 함", "No selection"),
    ("예약 {opt.todayInventory.reservedQty}", "Reserved {opt.todayInventory.reservedQty}"),
    # Predictions comparison  
    ("실적 비교", "performance comparison"),
    # Weather icon comments
    ("/구름조금|partly cloudy|약간흐림|few clouds/i", "/partly cloudy|약간흐림|few clouds/i"),
    ("/뇌우|thunderstorm|storm/i", "/thunderstorm|storm/i"),
    ("/눈|snow|blizzard/i", "/snow|blizzard/i"),
    ("/맑음|sunny|clear|화창/i", "/sunny|clear/i"),
    ("/바람|windy|강풍/i", "/windy/i"),
    ("/비|rain|shower|drizzle|소나기|이슬비/i", "/rain|shower|drizzle/i"),
    ("/안개|fog|mist/i", "/fog|mist/i"),
    ("/흐림|overcast|cloudy|구름많음|대체로흐림|mostly cloudy/i", "/overcast|cloudy|mostly cloudy/i"),
    # Holiday index
    ("뉴질랜드", "New Zealand"),
    # Prediction service
    ("개 생산을 추천합니다", " production units recommended"),
    # admin page  
    ("{formatDate(new Date(dailyRecord.date))} 보기 →", "{formatDate(new Date(dailyRecord.date))} View →"),
    # Remaining individual Korean terms not yet caught
    ("비중", "share"),
    ("기록 수", "records"),
    ("방향", "direction"),
    ("증가", "increase"),
    ("감소", "decrease"),
    ("합계", "Total"),
    ("전송", "Send"),
    ("불러오는 중...", "Loading..."),
    ("불러오는데", "loading"),
    ("예약", "Reserved"),
    ("연결관계", "relationships"),
    ("공통", "common"),
    ("최신", "latest"),
    ("이전", "previous"),
    ("임포트", "import"),
    ("임포트 중", "importing"),
    ("임포트 결과", "import result"),
    ("임포트 실행", "run import"),
    ("임포트 시작", "start import"),
    ("파싱된", "parsed"),
    ("에러", "error"),
    ("판매", "Sold"),
    ("현장", "on-site"),
    ("도메인", "domain"),
    ("특수문자", "special characters"),
    ("이메일", "email"),
    ("별칭", "alias"),
    ("아이디", "ID"),
    ("이미 사용됨", "already in use"),
    # Loyverse comment  
    ("# Loyverse POS 연동", "# Loyverse POS Integration"),
    # misc
    ("saveLabel", "saveLabel"),  # not Korean, skip
    ("Canterbury, Auckland", "Canterbury, Auckland"),  # already English
    # Remaining single words that may be standalone
    ("맑음", "Clear"),
    ("흐림", "Cloudy"),
    ("구름", "Clouds"),
    ("뇌우", "Thunderstorm"),
    ("눈", "Snow"),
    ("안개", "Fog"),
    ("비 오는 날", "Rainy days"),
    ("맑은 날", "Clear days"),
    ("일반일", "Regular days"),
    ("학기 중", "In-term"),
    ("요약", "Summary"),
    ("유형", "Type"),
    ("오류", "Error"),
    ("경고", "Warning"),
    ("정보", "Info"),
    ("항목", "Item"),
    ("내용", "Content"),
    ("결과", "Result"),
    ("요청", "Request"),
    ("응답", "Response"),
    ("처리", "Processing"),
    ("실행", "Run"),
    ("이전", "Previous"),
    ("다음", "Next"),
    ("부분", "Partial"),
    ("완전", "Full"),
    ("전체", "All"),
    ("완료", "Completed"),
    ("성공", "Success"),
    ("실패", "Failed"),
    ("수집", "Collect"),
    ("생성", "Created"),
    ("수정", "Updated"),
    ("삭제", "Deleted"),
    ("연결", "Linked"),
    ("해제", "Unlinked"),
    ("적용", "Applied"),
    ("반영", "Reflected"),
    ("업데이트", "Updated"),
    ("갱신", "Refreshed"),
    ("초기화", "Reset"),
    ("확인", "Confirm"),
    ("취소", "Cancel"),
    ("추가", "Add"),
    ("제거", "Remove"),
    ("저장", "Save"),
    ("닫기", "Close"),
    ("열기", "Open"),
    ("펼치기", "Expand"),
    ("접기", "Collapse"),
    ("돌아가기", "Back"),
    ("이동", "Go"),
    ("전환", "Switch"),
    ("선택", "Select"),
    ("입력", "Enter"),
    ("검색", "Search"),
    ("필터", "Filter"),
    ("정렬", "Sort"),
    ("보기", "View"),
    ("숨기기", "Hide"),
    ("표시", "Show"),
    ("복사", "Copy"),
    ("붙여넣기", "Paste"),
    ("다운로드", "Download"),
    ("업로드", "Upload"),
    ("내보내기", "Export"),
    ("가져오기", "Import"),
    ("동기화", "Sync"),
    ("새로고침", "Refresh"),
    ("재시도", "Retry"),
    ("취소", "Cancel"),
    ("설정", "Settings"),
    ("권한", "Permission"),
    ("역할", "Role"),
    ("사용자", "User"),
    ("관리자", "Admin"),
    ("직원", "Staff"),
    ("고객", "Customer"),
    ("구독", "Subscription"),
    ("주문", "Order"),
    ("상품", "Product"),
    ("카테고리", "Category"),
    ("재고", "Inventory"),
    ("판매", "Sales"),
    ("예측", "Prediction"),
    ("분석", "Analytics"),
    ("가중치", "Weight"),
    ("외부", "External"),
    ("내부", "Internal"),
    ("자동", "Auto"),
    ("수동", "Manual"),
    ("활성", "Active"),
    ("비활성", "Inactive"),
    ("활성화", "Activate"),
    ("비활성화", "Deactivate"),
    ("사용 가능", "Available"),
    ("사용 불가", "Unavailable"),
    ("무료", "Free"),
    ("유료", "Paid"),
    ("필수", "Required"),
    ("선택", "Optional"),
    ("기본", "Default"),
    ("사용자 정의", "Custom"),
    ("즉시", "Immediate"),
    ("예약", "Scheduled"),
    ("반복", "Recurring"),
    ("일회성", "One-time"),
    ("매일", "Daily"),
    ("매주", "Weekly"),
    ("매월", "Monthly"),
    ("매년", "Yearly"),
]

# Second set of regex patterns
REGEX_FIXES = [
    # Dynamic day of week patterns
    (r'Every \$\{WEEKDAYS\[([^\]]+)\]\}요일', r'Every ${\1}'),
    (r'Every \$\{([^\}]+)\}요일', r'Every ${\1}'),
    (r'\$\{([^\}]+)\}요일', r'${\1}'),
    # 개 suffix in template literals
    (r'\$\{([^\}]+)\}개(?=[\s`\'",<{;)])', r'${\1}'),
    (r'(\{[^}]+\})개(?=\s*<)', r'\1'),
    # 일 count suffix  
    (r'\$\{([^\}]+)\}일(?=[\s`\'",<{;)>])', r'${\1} days'),
    # items suffix in counts (remaining from 건 → items)
    (r'\$\{([^\}]+)\}items(?=[\s`\'",<{;)>])', r'${\1}'),
    # 원 (currency unit after numbers)  
    (r'\(([^)]+)원\)', r'($\1)'),
]

def process_file(filepath: str) -> bool:
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
    except (UnicodeDecodeError, IOError):
        return False
    
    original = content
    
    # Apply regex fixes
    for pattern, replacement in REGEX_FIXES:
        content = re.sub(pattern, replacement, content)
    
    # Apply literal fixes
    for old, new in GARBLED_FIXES:
        content = content.replace(old, new)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False


def main():
    result = subprocess.run(
        ["find", PROJECT_ROOT, "-type", "f", "(", "-name", "*.ts", "-o", "-name", "*.tsx", ")"],
        capture_output=True, text=True
    )
    all_files = [f for f in result.stdout.strip().split('\n') if f and 'node_modules' not in f and '.next' not in f and 'scripts/' not in f]
    
    changed = 0
    for filepath in all_files:
        # Only process files with Korean
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            if not re.search(r'[가-힣ㄱ-ㅎㅏ-ㅣ]', content):
                continue
        except (UnicodeDecodeError, IOError):
            continue
        
        if process_file(filepath):
            rel = filepath.replace(PROJECT_ROOT + '/', '')
            print(f"  FIXED: {rel}")
            changed += 1
    
    print(f"\nTotal fixed: {changed} files")

if __name__ == "__main__":
    main()
